import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch all user trades
    const trades = await base44.entities.TradeChecklist.list('-created_date', 1000);
    
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(24);
    doc.text('ZNPCV Profile Export', 20, 20);
    
    doc.setFontSize(10);
    doc.text(`Name: ${user.full_name || '-'}`, 20, 35);
    doc.text(`Email: ${user.email}`, 20, 42);
    doc.text(`Role: ${user.role?.toUpperCase() || 'USER'}`, 20, 49);
    doc.text(`Member Since: ${new Date(user.created_date).toLocaleDateString()}`, 20, 56);
    doc.text(`Export Date: ${new Date().toLocaleDateString()}`, 20, 63);
    
    // Statistics
    doc.setFontSize(16);
    doc.text('Trading Statistics', 20, 80);
    
    const executed = trades.filter(t => t.outcome && t.outcome !== 'pending');
    const wins = executed.filter(t => t.outcome === 'win').length;
    const losses = executed.filter(t => t.outcome === 'loss').length;
    const totalPnL = executed.reduce((sum, t) => sum + parseFloat(t.actual_pnl || 0), 0);
    const winRate = executed.length > 0 ? ((wins / executed.length) * 100).toFixed(1) : 0;
    
    doc.setFontSize(10);
    doc.text(`Total Trades: ${trades.length}`, 20, 95);
    doc.text(`Executed Trades: ${executed.length}`, 20, 102);
    doc.text(`Wins: ${wins}`, 20, 109);
    doc.text(`Losses: ${losses}`, 20, 116);
    doc.text(`Win Rate: ${winRate}%`, 20, 123);
    doc.text(`Total P&L: $${totalPnL.toFixed(2)}`, 20, 130);
    
    // Recent Trades
    doc.setFontSize(16);
    doc.text('Recent Trades (Last 20)', 20, 150);
    
    doc.setFontSize(9);
    let y = 165;
    const recentTrades = trades.slice(0, 20);
    
    recentTrades.forEach((trade, idx) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      
      const date = new Date(trade.trade_date || trade.created_date).toLocaleDateString();
      const outcome = trade.outcome || 'pending';
      const pnl = trade.actual_pnl || '-';
      
      doc.text(`${idx + 1}. ${trade.pair} | ${trade.direction?.toUpperCase()} | ${date}`, 20, y);
      doc.text(`Status: ${outcome} | P&L: $${pnl} | Score: ${trade.completion_percentage || 0}%`, 25, y + 5);
      
      y += 15;
    });
    
    // Footer
    doc.setFontSize(8);
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(`Page ${i} of ${pageCount}`, 180, 285);
      doc.text('Generated by ZNPCV', 20, 285);
    }
    
    const pdfBytes = doc.output('arraybuffer');
    
    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=ZNPCV_Profile_${user.email}_${new Date().toISOString().split('T')[0]}.pdf`
      }
    });
  } catch (error) {
    console.error('Export failed:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});