import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  zh: {
    // 简体中文 - VOLLSTÄNDIG
    online: '在线',
    localTime: '本地时间',
    myAccount: '我的账户',
    logout: '登出',
    login: '登录',
    editProfile: '编辑资料',
    save: '保存',
    ultimateChecklist: '终极检查清单',
    tradingTools: '终极交易工具',
    disciplineQuote: '纪律胜过天赋。每一天。',
    philosophy: 'ZNPCV 哲学',
    newAnalysis: '新分析',
    newAnalysisDesc: '使用终极ZNPCV检查清单开始你的专业多时间框架分析',
    startNow: '立即开始',
    dashboard: '仪表板',
    dashboardDesc: '分析概览、绩效跟踪和详细统计',
    openDashboard: '打开',
    marketSessions: '市场时段',
    features: '功能',
    featuresDesc: '专业交易工具',
    preciseAnalysis: '精确分析',
    preciseAnalysisDesc: 'W-D-4H汇合系统，实现最高准确度',
    riskManagement: '风险管理',
    riskManagementDesc: '集成R:R评估和SL/TP规划',
    performanceTracking: '绩效跟踪',
    performanceTrackingDesc: '详细统计和成功率',
    znpcvStandard: 'ZNPCV标准',
    stepChecklist: '步骤检查清单',
    chartPatterns: '图表模式',
    contact: '联系',
    faqHelp: '常见问题和帮助',
    footerDesc: '专业交易者的终极交易检查清单。为最大纪律和一致结果而开发。',
    riskWarning: '交易涉及风险。过往结果不保证未来利润。',
    allRights: '版权所有。',
    tradingDashboard: '交易仪表板',
    overviewStats: '概览与绩效',
    totalAnalyses: '总分析',
    readyToTradeShort: '就绪',
    inProgress: '进行中',
    withConfluence: '有汇合',
    activity30Days: '活动（30天）',
    lastAnalyses: '最新分析',
    calendar: '日历',
    avgCompletion: '平均完成度',
    loading: '加载中...',
    noAnalyses: '无分析',
    startFirstAnalysis: '开始第一个分析',
    assetDirection: '资产和方向',
    selectPairDirection: '选择你的交易对和交易方向',
    goldenRules: 'ZNPCV黄金法则',
    goldenRuleText: '永远不在阻力位买入。永远不在支撑位卖出。买入交易只能在AOI内或上方进行（支撑区）。卖出交易只能在AOI内或下方进行（阻力区）。',
    longBuyRule: '我们在AOI内或上方买入（支撑）',
    shortSellRule: '我们在AOI内或下方卖出（阻力）',
    neverBottomTop: '永远不要在底部卖出！永远不要在顶部买入！',
    selectDirection: '选择你的方向',
    buyInAoi: '在/上方AOI买入',
    sellInAoi: '在/下方AOI卖出',
    weeklyAnalysis: '周线分析',
    weeklyConfirm: '周线时间框架确认（最多60%）',
    weeklyScore: '周线得分',
    weeklyTrend: '周线趋势（看涨/看跌）',
    atAoiRejected: '在AOI/被拒绝',
    atAoiDesc: '价格在AOI或价格拒绝AOI',
    touchingEma: '触碰/拒绝EMA',
    touchingEmaDesc: '蜡烛触碰或拒绝EMA',
    candlestickRejection: '蜡烛拒绝',
    candlestickDesc: '蜡烛显示明显拒绝（Pinbar、Doji、Hammer）',
    rejectionPsp: '从PSP拒绝',
    rejectionPspDesc: '从先前结构点拒绝',
    roundLevel: '整数心理水平',
    roundLevelDesc: '价格在整数或拒绝整数',
    swingHighLow: '摆动高点/低点',
    swingDesc: '价格到达摆动高点或摆动低点',
    patternWeekly: '模式（周线）',
    patternDesc: '双顶/双底、正常/倒置头肩',
    dailyAnalysis: '日线分析',
    dailyConfirm: '日线时间框架确认（最多60%）',
    dailyScore: '日线得分',
    dailyTrend: '日线趋势（看涨/看跌）',
    h4Analysis: '4小时分析',
    h4Confirm: '较低时间框架确认（最多35%）',
    h4Score: '4小时得分',
    h4Trend: '4小时趋势（看涨/看跌）',
    entryChecklist: '入场检查清单',
    entryConfirm: '入场确认（最多25%）',
    entryTimeframe: '入场时间框架',
    entryTimeframeDesc: '选择30分钟或1小时时间框架 - 取决于哪个提供最清晰的结构和最精确的入场点。我们是波段/日内交易者，专注于更高的时间框架，而非剥头皮交易者。',
    entryScoreLabel: '入场得分',
    mssShift: 'MSS - 市场结构转变',
    mssDesc: '结构转变/市场结构已转变（30分钟-1小时）',
    engulfingCandle: '吞没蜡烛',
    engulfingDesc: '回调后可见吞没蜡烛（反转确认）',
    patternIfAny: '模式（如果有）',
    patternIfAnyDesc: '如果入场时间框架上可见模式',
    entryTrigger: '入场触发类型',
    pinbarRejection: 'PINBAR拒绝',
    engulfing: '吞没',
    riskManagementTitle: '风险管理',
    riskManagementSubtitle: '头寸大小和手数计算器',
    finalCheckTitle: '最终检查',
    finalCheckSubtitle: '交易前的最终确认',
    confirmRule: '确认ZNPCV规则',
    buyInAboveAoi: '我在AOI内或上方买入',
    notBuyResistance: '我不在阻力/顶部买入',
    sellInBelowAoi: '我在AOI内或下方卖出',
    notSellSupport: '我不在支撑/底部卖出',
    selectDirFirst: '首先在第一步选择方向',
    tradeSummary: '交易摘要',
    notesOptional: '备注（可选）',
    notesPlaceholderLong: '交易备注、观察...',
    readyToTradeLabel: '准备交易',
    notRecommended: 'ZNPCV建议不要交易（最少85%）',
    pointsBreakdown: '分数细分',
    total: '总计',
    saveTrade: '保存交易',
    warningScore: '您的得分低于85%。根据ZNPCV标准，您不应该进行此交易。',
    doNotEnter: '不要进入交易',
    saveAnyway: '仍然保存',
    back: '返回',
    next: '下一步',
    saving: '保存中...',
    direction: '方向',
    long: '买入',
    short: '卖出',
    of: '的',
    dblTop: '双顶',
    dblBtm: '双底',
    hs: '头肩',
    invHs: '倒置头肩',
    none: '无',
    accountSize: '账户规模',
    riskPercent: '风险%',
    entryPrice: '入场价格',
    stopLoss: '止损',
    takeProfit: '止盈',
    lotSizeCalc: '手数计算器',
    recommendedLotSize: '推荐手数',
    standardLots: '标准手',
    miniLots: '迷你手',
    microLots: '微型手',
    units: '单位',
    riskAmount: '风险金额$',
    slPips: '止损点数',
    tpPips: '止盈点数',
    potentialProfit: '潜在利润',
    rrRatio: '风险回报比',
    quickRisk: '快速风险选择',
    lotSizeInfo: '根据您的风险计算精确手数。输入入场价和止损以查看推荐头寸。',
    enterEntryAndSL: '输入入场价格和止损以计算您的手数',
    minRRWarning: 'ZNPCV建议至少1:2.5的风险回报比',
    goodRR: '良好的风险回报比！',
    tradeLevels: '交易水平',
    tradeHistory: '交易历史',
    performanceAnalytics: '绩效分析与交易记录',
    allTrades: '所有交易',
    winLoss: '胜/负',
    avgWinLoss: '平均胜负',
    avgWin: '平均盈利',
    avgLoss: '平均亏损',
    profitFactor: '利润因子',
    avgRR: '平均风险回报',
    bestTrade: '最佳交易',
    consistency: '一致性',
    trades: '交易',
    executed: '已执行',
    pending: '待处理',
    confirmDelete: '确定要删除此交易吗？',
    furtherQuestions: '还有其他问题吗？',
    contactUs: '如有其他问题，请直接联系我们',
  },
  es: {
    // Español - VOLLSTÄNDIG
    online: 'EN LÍNEA',
    localTime: 'HORA LOCAL',
    myAccount: 'MI CUENTA',
    logout: 'CERRAR SESIÓN',
    login: 'INICIAR SESIÓN',
    editProfile: 'EDITAR PERFIL',
    save: 'GUARDAR',
    ultimateChecklist: 'CHECKLIST DEFINITIVO',
    tradingTools: 'LA HERRAMIENTA DEFINITIVA',
    disciplineQuote: 'La disciplina vence al talento. Todos. Los. Días.',
    philosophy: 'FILOSOFÍA ZNPCV',
    newAnalysis: 'NUEVO ANÁLISIS',
    newAnalysisDesc: 'Inicia tu análisis profesional multi-timeframe con el checklist definitivo ZNPCV',
    startNow: 'Comenzar ahora',
    dashboard: 'PANEL',
    dashboardDesc: 'Vista general de tus análisis, seguimiento de rendimiento y estadísticas detalladas',
    openDashboard: 'Abrir',
    marketSessions: 'SESIONES DE MERCADO',
    features: 'CARACTERÍSTICAS',
    featuresDesc: 'Herramientas de Trading Profesionales',
    preciseAnalysis: 'ANÁLISIS PRECISO',
    preciseAnalysisDesc: 'Sistema de Confluencia W-D-4H para máxima precisión',
    riskManagement: 'GESTIÓN DE RIESGO',
    riskManagementDesc: 'Evaluación integrada R:R y planificación SL/TP',
    performanceTracking: 'SEGUIMIENTO DE RENDIMIENTO',
    performanceTrackingDesc: 'Estadísticas detalladas y tasas de éxito',
    znpcvStandard: 'ESTÁNDAR ZNPCV',
    stepChecklist: 'CHECKLIST DE PASOS',
    chartPatterns: 'PATRONES DE GRÁFICO',
    contact: 'CONTACTO',
    faqHelp: 'PREGUNTAS FRECUENTES Y AYUDA',
    footerDesc: 'El checklist de trading definitivo para traders profesionales. Desarrollado para máxima disciplina y resultados consistentes.',
    riskWarning: 'El trading implica riesgos. Los resultados pasados no garantizan ganancias futuras.',
    allRights: 'Todos los derechos reservados.',
    tradingDashboard: 'PANEL DE TRADING',
    overviewStats: 'VISTA GENERAL Y RENDIMIENTO',
    totalAnalyses: 'ANÁLISIS TOTALES',
    readyToTradeShort: 'LISTO',
    inProgress: 'EN PROGRESO',
    withConfluence: 'CON CONFLUENCIA',
    activity30Days: 'ACTIVIDAD (30 DÍAS)',
    lastAnalyses: 'ÚLTIMOS ANÁLISIS',
    calendar: 'CALENDARIO',
    avgCompletion: 'COMPLETITUD PROMEDIO',
    loading: 'CARGANDO...',
    noAnalyses: 'SIN ANÁLISIS',
    startFirstAnalysis: 'INICIAR PRIMER ANÁLISIS',
    assetDirection: 'ACTIVO Y DIRECCIÓN',
    selectPairDirection: 'Selecciona tu par de trading y dirección',
    goldenRules: 'REGLA DORADA ZNPCV',
    goldenRuleText: 'Nunca comprar en resistencia. Nunca vender en soporte. Un trade LONG solo se ejecuta en o sobre el AOI (zona de soporte). Un trade SHORT solo se ejecuta en o bajo el AOI (zona de resistencia).',
    longBuyRule: 'Compramos EN o SOBRE el AOI (Soporte)',
    shortSellRule: 'Vendemos EN o BAJO el AOI (Resistencia)',
    neverBottomTop: '¡NUNCA VENDER EN EL FONDO! ¡NUNCA COMPRAR EN EL TOP!',
    selectDirection: 'SELECCIONA TU DIRECCIÓN',
    buyInAoi: 'Comprar en/sobre AOI',
    sellInAoi: 'Vender en/bajo AOI',
    weeklyAnalysis: 'ANÁLISIS SEMANAL',
    weeklyConfirm: 'Confirmaciones de Marco Temporal Semanal (máx 60%)',
    weeklyScore: 'PUNTUACIÓN SEMANAL',
    weeklyTrend: 'TENDENCIA SEMANAL (ALCISTA / BAJISTA)',
    atAoiRejected: 'EN AOI / RECHAZADO',
    atAoiDesc: 'Precio está en AOI O Precio rechaza AOI',
    touchingEma: 'TOCANDO / RECHAZANDO EMA',
    touchingEmaDesc: 'Las velas tocan O rechazan el EMA',
    candlestickRejection: 'RECHAZO DE VELA',
    candlestickDesc: 'La vela muestra rechazo claro (Pinbar, Doji, Hammer)',
    rejectionPsp: 'RECHAZO DESDE PSP',
    rejectionPspDesc: 'Rechazo desde Punto de Estructura Anterior',
    roundLevel: 'NIVEL PSICOLÓGICO REDONDO',
    roundLevelDesc: 'Precio está en O rechaza número redondo',
    swingHighLow: 'SWING ALTO / SWING BAJO',
    swingDesc: 'Precio ha alcanzado Swing Alto O Swing Bajo',
    patternWeekly: 'PATRÓN (SEMANAL)',
    patternDesc: 'Doble Techo/Fondo, H&S Normal/Invertido',
    dailyAnalysis: 'ANÁLISIS DIARIO',
    dailyConfirm: 'Confirmaciones de Marco Temporal Diario (máx 60%)',
    dailyScore: 'PUNTUACIÓN DIARIA',
    dailyTrend: 'TENDENCIA DIARIA (ALCISTA / BAJISTA)',
    h4Analysis: 'ANÁLISIS 4H',
    h4Confirm: 'Confirmación de Marco Temporal Inferior (máx 35%)',
    h4Score: 'PUNTUACIÓN 4H',
    h4Trend: 'TENDENCIA 4H (ALCISTA / BAJISTA)',
    entryChecklist: 'CHECKLIST DE ENTRADA',
    entryConfirm: 'Confirmaciones de Entrada (máx 25%)',
    entryTimeframe: 'MARCO TEMPORAL DE ENTRADA',
    entryTimeframeDesc: 'Elige entre 30min o 1H - según cuál proporcione la estructura más limpia y la entrada más precisa. Somos traders de Swing/Day enfocados en marcos temporales superiores, no scalpers.',
    entryScoreLabel: 'PUNTUACIÓN DE ENTRADA',
    mssShift: 'MSS - CAMBIO DE ESTRUCTURA DE MERCADO',
    mssDesc: 'Cambio de Estructura / La estructura del mercado ha cambiado (30min-1hr)',
    engulfingCandle: 'VELA ENVOLVENTE',
    engulfingDesc: 'Vela envolvente visible después del retroceso (Confirmación de Reversión)',
    patternIfAny: 'PATRÓN (SI HAY UNO)',
    patternIfAnyDesc: 'Si hay un patrón visible en el TF de Entrada',
    entryTrigger: 'TIPO DE TRIGGER DE ENTRADA',
    pinbarRejection: 'RECHAZO PINBAR',
    engulfing: 'ENVOLVENTE',
    riskManagementTitle: 'GESTIÓN DE RIESGO',
    riskManagementSubtitle: 'Tamaño de Posición y Calculadora de Lotes',
    finalCheckTitle: 'COMPROBACIÓN FINAL',
    finalCheckSubtitle: 'Confirmación final antes del trade',
    confirmRule: 'CONFIRMA LA REGLA ZNPCV',
    buyInAboveAoi: 'COMPRO EN O SOBRE EL AOI',
    notBuyResistance: 'NO compro en resistencia / techo',
    sellInBelowAoi: 'VENDO EN O BAJO EL AOI',
    notSellSupport: 'NO vendo en soporte / suelo',
    selectDirFirst: 'Selecciona primero una dirección en el primer paso',
    tradeSummary: 'RESUMEN DEL TRADE',
    notesOptional: 'NOTAS (OPCIONAL)',
    notesPlaceholderLong: 'Notas del trade, observaciones...',
    readyToTradeLabel: 'LISTO PARA OPERAR',
    notRecommended: 'ZNPCV recomienda NO operar (mín. 85%)',
    pointsBreakdown: 'DESGLOSE DE PUNTOS',
    total: 'TOTAL',
    saveTrade: 'GUARDAR OPERACIÓN',
    warningScore: 'Tu puntuación está por debajo del 85%. Según el estándar ZNPCV, NO deberías entrar en este trade.',
    doNotEnter: 'NO ENTRAR EN EL TRADE',
    saveAnyway: 'Guardar de todos modos',
    back: 'ATRÁS',
    next: 'SIGUIENTE',
    saving: 'GUARDANDO...',
    direction: 'DIRECCIÓN',
    long: 'LARGO',
    short: 'CORTO',
    of: 'DE',
    dblTop: 'DOBLE TECHO',
    dblBtm: 'DOBLE FONDO',
    hs: 'H&S',
    invHs: 'H&S INV',
    none: 'NINGUNO',
    accountSize: 'TAMAÑO DE CUENTA',
    riskPercent: 'RIESGO %',
    entryPrice: 'PRECIO DE ENTRADA',
    stopLoss: 'STOP LOSS',
    takeProfit: 'TAKE PROFIT',
    lotSizeCalc: 'CALCULADORA DE LOTES',
    recommendedLotSize: 'TAMAÑO DE LOTE RECOMENDADO',
    standardLots: 'Lotes Estándar',
    miniLots: 'MINI LOTES',
    microLots: 'MICRO LOTES',
    units: 'UNIDADES',
    riskAmount: 'RIESGO $',
    slPips: 'PIPS SL',
    tpPips: 'PIPS TP',
    potentialProfit: 'BENEFICIO POTENCIAL',
    rrRatio: 'RATIO R:R',
    quickRisk: 'SELECCIÓN RÁPIDA DE RIESGO',
    lotSizeInfo: 'Calcula tu tamaño de lote exacto según tu riesgo. Introduce Entrada y Stop Loss para ver la posición recomendada.',
    enterEntryAndSL: 'Introduce Precio de Entrada y Stop Loss para calcular tu Tamaño de Lote',
    minRRWarning: 'ZNPCV recomienda al menos ratio 1:2.5 R:R',
    goodRR: '¡Buen ratio Riesgo:Recompensa!',
    tradeLevels: 'NIVELES DE TRADE',
    tradeHistory: 'HISTORIAL DE TRADES',
    performanceAnalytics: 'Análisis de Rendimiento y Registro de Trades',
    allTrades: 'TODOS LOS TRADES',
    winLoss: 'GANANCIAS/PÉRDIDAS',
    avgWinLoss: 'PROMEDIO WIN/LOSS',
    avgWin: 'PROMEDIO GANANCIA',
    avgLoss: 'PROMEDIO PÉRDIDA',
    profitFactor: 'FACTOR DE BENEFICIO',
    avgRR: 'PROMEDIO R:R',
    bestTrade: 'MEJOR TRADE',
    consistency: 'CONSISTENCIA',
    trades: 'TRADES',
    executed: 'EJECUTADOS',
    pending: 'PENDIENTE',
    confirmDelete: '¿Realmente eliminar el trade?',
    furtherQuestions: '¿MÁS PREGUNTAS?',
    contactUs: 'Si tienes más preguntas, contáctanos directamente',
  },
  fr: {
    // Français - VOLLSTÄNDIG
    online: 'EN LIGNE',
    localTime: 'HEURE LOCALE',
    myAccount: 'MON COMPTE',
    logout: 'DÉCONNEXION',
    login: 'CONNEXION',
    editProfile: 'ÉDITER LE PROFIL',
    save: 'ENREGISTRER',
    ultimateChecklist: 'CHECKLIST ULTIME',
    tradingTools: "L'OUTIL ULTIME",
    disciplineQuote: 'La discipline bat le talent. Chaque. Jour.',
    philosophy: 'PHILOSOPHIE ZNPCV',
    newAnalysis: 'NOUVELLE ANALYSE',
    newAnalysisDesc: 'Commencez votre analyse professionnelle multi-timeframe avec la checklist ultime ZNPCV',
    startNow: 'Commencer maintenant',
    dashboard: 'TABLEAU DE BORD',
    dashboardDesc: 'Vue d\'ensemble de vos analyses, suivi des performances et statistiques détaillées',
    openDashboard: 'Ouvrir',
    marketSessions: 'SESSIONS DE MARCHÉ',
    features: 'FONCTIONNALITÉS',
    featuresDesc: 'Outils de Trading Professionnels',
    preciseAnalysis: 'ANALYSE PRÉCISE',
    preciseAnalysisDesc: 'Système de Confluence W-D-4H pour une précision maximale',
    riskManagement: 'GESTION DES RISQUES',
    riskManagementDesc: 'Évaluation intégrée R:R et planification SL/TP',
    performanceTracking: 'SUIVI DES PERFORMANCES',
    performanceTrackingDesc: 'Statistiques détaillées et taux de réussite',
    znpcvStandard: 'STANDARD ZNPCV',
    stepChecklist: 'CHECKLIST D\'ÉTAPES',
    chartPatterns: 'MODÈLES DE GRAPHIQUE',
    contact: 'CONTACT',
    faqHelp: 'FAQ ET AIDE',
    footerDesc: 'La checklist de trading ultime pour les traders professionnels. Développée pour une discipline maximale et des résultats cohérents.',
    riskWarning: 'Le trading comporte des risques. Les résultats passés ne garantissent pas les profits futurs.',
    allRights: 'Tous droits réservés.',
    tradingDashboard: 'TABLEAU DE BORD TRADING',
    overviewStats: 'VUE D\'ENSEMBLE ET PERFORMANCE',
    totalAnalyses: 'ANALYSES TOTALES',
    readyToTradeShort: 'PRÊT',
    inProgress: 'EN COURS',
    withConfluence: 'AVEC CONFLUENCE',
    activity30Days: 'ACTIVITÉ (30 JOURS)',
    lastAnalyses: 'DERNIÈRES ANALYSES',
    calendar: 'CALENDRIER',
    avgCompletion: 'COMPLÉTION MOYENNE',
    loading: 'CHARGEMENT...',
    noAnalyses: 'AUCUNE ANALYSE',
    startFirstAnalysis: 'COMMENCER LA PREMIÈRE ANALYSE',
    assetDirection: 'ACTIF ET DIRECTION',
    selectPairDirection: 'Sélectionnez votre paire de trading et la direction',
    goldenRules: 'RÈGLE D\'OR ZNPCV',
    goldenRuleText: 'Jamais acheter à la résistance. Jamais vendre au support. Un trade LONG est uniquement pris dans ou au-dessus de l\'AOI (zone de support). Un trade SHORT est uniquement pris dans ou en-dessous de l\'AOI (zone de résistance).',
    longBuyRule: 'Nous achetons DANS ou AU-DESSUS de l\'AOI (Support)',
    shortSellRule: 'Nous vendons DANS ou EN-DESSOUS de l\'AOI (Résistance)',
    neverBottomTop: 'JAMAIS VENDRE AU BAS! JAMAIS ACHETER AU HAUT!',
    selectDirection: 'SÉLECTIONNEZ VOTRE DIRECTION',
    buyInAoi: 'Acheter dans/au-dessus AOI',
    sellInAoi: 'Vendre dans/en-dessous AOI',
    weeklyAnalysis: 'ANALYSE HEBDOMADAIRE',
    weeklyConfirm: 'Confirmations Timeframe Hebdomadaire (max 60%)',
    weeklyScore: 'SCORE HEBDOMADAIRE',
    weeklyTrend: 'TENDANCE HEBDOMADAIRE (HAUSSIER / BAISSIER)',
    atAoiRejected: 'À L\'AOI / REJETÉ',
    atAoiDesc: 'Le prix est à l\'AOI OU Le prix rejette l\'AOI',
    touchingEma: 'TOUCHER / REJETER EMA',
    touchingEmaDesc: 'Les bougies touchent OU rejettent l\'EMA',
    candlestickRejection: 'REJET DE BOUGIE',
    candlestickDesc: 'La bougie montre un rejet clair (Pinbar, Doji, Hammer)',
    rejectionPsp: 'REJET DEPUIS PSP',
    rejectionPspDesc: 'Rejet depuis le Point de Structure Précédent',
    roundLevel: 'NIVEAU PSYCHOLOGIQUE ROND',
    roundLevelDesc: 'Le prix est à OU rejette un nombre rond',
    swingHighLow: 'SWING HAUT / SWING BAS',
    swingDesc: 'Le prix a atteint Swing Haut OU Swing Bas',
    patternWeekly: 'MODÈLE (HEBDOMADAIRE)',
    patternDesc: 'Double Sommet/Creux, Tête et Épaules Normal/Inversé',
    dailyAnalysis: 'ANALYSE QUOTIDIENNE',
    dailyConfirm: 'Confirmations Timeframe Quotidien (max 60%)',
    dailyScore: 'SCORE QUOTIDIEN',
    dailyTrend: 'TENDANCE QUOTIDIENNE (HAUSSIER / BAISSIER)',
    h4Analysis: 'ANALYSE 4H',
    h4Confirm: 'Confirmation Timeframe Inférieur (max 35%)',
    h4Score: 'SCORE 4H',
    h4Trend: 'TENDANCE 4H (HAUSSIER / BAISSIER)',
    entryChecklist: 'CHECKLIST D\'ENTRÉE',
    entryConfirm: 'Confirmations d\'Entrée (max 25%)',
    entryTimeframe: 'TIMEFRAME D\'ENTRÉE',
    entryTimeframeDesc: 'Choisissez entre 30min ou 1H - selon celui qui fournit la structure la plus propre et l\'entrée la plus précise. Nous sommes des traders Swing/Day concentrés sur les timeframes supérieurs, pas des scalpers.',
    entryScoreLabel: 'SCORE D\'ENTRÉE',
    mssShift: 'MSS - CHANGEMENT DE STRUCTURE DE MARCHÉ',
    mssDesc: 'Changement de Structure / La structure du marché a changé (30min-1hr)',
    engulfingCandle: 'BOUGIE ENGLOBANTE',
    engulfingDesc: 'Bougie englobante visible après le pullback (Confirmation de Retournement)',
    patternIfAny: 'MODÈLE (S\'IL Y EN A UN)',
    patternIfAnyDesc: 'Si un modèle est visible sur le TF d\'Entrée',
    entryTrigger: 'TYPE DE DÉCLENCHEUR D\'ENTRÉE',
    pinbarRejection: 'REJET PINBAR',
    engulfing: 'ENGLOBANT',
    riskManagementTitle: 'GESTION DES RISQUES',
    riskManagementSubtitle: 'Dimensionnement de Position et Calculateur de Lot',
    finalCheckTitle: 'VÉRIFICATION FINALE',
    finalCheckSubtitle: 'Confirmation finale avant le trade',
    confirmRule: 'CONFIRMEZ LA RÈGLE ZNPCV',
    buyInAboveAoi: 'J\'ACHÈTE DANS OU AU-DESSUS DE L\'AOI',
    notBuyResistance: 'Je n\'achète PAS à la résistance / sommet',
    sellInBelowAoi: 'JE VENDS DANS OU EN-DESSOUS DE L\'AOI',
    notSellSupport: 'Je ne vends PAS au support / creux',
    selectDirFirst: 'Sélectionnez d\'abord une direction dans la première étape',
    tradeSummary: 'RÉSUMÉ DU TRADE',
    notesOptional: 'NOTES (OPTIONNEL)',
    notesPlaceholderLong: 'Notes du trade, observations...',
    readyToTradeLabel: 'PRÊT À TRADER',
    notRecommended: 'ZNPCV recommande de NE PAS trader (min. 85%)',
    pointsBreakdown: 'RÉPARTITION DES POINTS',
    total: 'TOTAL',
    saveTrade: 'ENREGISTRER LE TRADE',
    warningScore: 'Votre score est inférieur à 85%. Selon le standard ZNPCV, vous NE devriez PAS entrer dans ce trade.',
    doNotEnter: 'NE PAS ENTRER DANS LE TRADE',
    saveAnyway: 'Enregistrer quand même',
    back: 'RETOUR',
    next: 'SUIVANT',
    saving: 'ENREGISTREMENT...',
    direction: 'DIRECTION',
    long: 'LONG',
    short: 'SHORT',
    of: 'DE',
    dblTop: 'DOUBLE SOMMET',
    dblBtm: 'DOUBLE CREUX',
    hs: 'T&É',
    invHs: 'T&É INV',
    none: 'AUCUN',
    accountSize: 'TAILLE DU COMPTE',
    riskPercent: 'RISQUE %',
    entryPrice: 'PRIX D\'ENTRÉE',
    stopLoss: 'STOP LOSS',
    takeProfit: 'TAKE PROFIT',
    lotSizeCalc: 'CALCULATEUR DE LOT',
    recommendedLotSize: 'TAILLE DE LOT RECOMMANDÉE',
    standardLots: 'Lots Standard',
    miniLots: 'MINI LOTS',
    microLots: 'MICRO LOTS',
    units: 'UNITÉS',
    riskAmount: 'RISQUE $',
    slPips: 'PIPS SL',
    tpPips: 'PIPS TP',
    potentialProfit: 'PROFIT POTENTIEL',
    rrRatio: 'RATIO R:R',
    quickRisk: 'SÉLECTION RAPIDE DU RISQUE',
    lotSizeInfo: 'Calculez votre taille de lot exacte selon votre risque. Entrez Entrée et Stop Loss pour voir la position recommandée.',
    enterEntryAndSL: 'Entrez le Prix d\'Entrée et le Stop Loss pour calculer votre Taille de Lot',
    minRRWarning: 'ZNPCV recommande au moins un ratio 1:2.5 R:R',
    goodRR: 'Bon ratio Risque:Récompense!',
    tradeLevels: 'NIVEAUX DE TRADE',
    tradeHistory: 'HISTORIQUE DES TRADES',
    performanceAnalytics: 'Analyse de Performance et Journal de Trading',
    allTrades: 'TOUS LES TRADES',
    winLoss: 'GAINS/PERTES',
    avgWinLoss: 'MOYENNE WIN/LOSS',
    avgWin: 'GAIN MOYEN',
    avgLoss: 'PERTE MOYENNE',
    profitFactor: 'FACTEUR DE PROFIT',
    avgRR: 'R:R MOYEN',
    bestTrade: 'MEILLEUR TRADE',
    consistency: 'CONSISTANCE',
    trades: 'TRADES',
    executed: 'EXÉCUTÉS',
    pending: 'EN ATTENTE',
    confirmDelete: 'Vraiment supprimer le trade?',
    furtherQuestions: 'D\'AUTRES QUESTIONS?',
    contactUs: 'Si vous avez d\'autres questions, contactez-nous directement',
  },
  hi: {
    // हिन्दी - VOLLSTÄNDIG
    online: 'ऑनलाइन',
    localTime: 'स्थानीय समय',
    myAccount: 'मेरा खाता',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    editProfile: 'प्रोफाइल संपादित करें',
    save: 'सहेजें',
    ultimateChecklist: 'अंतिम चेकलिस्ट',
    tradingTools: 'परम ट्रेडिंग टूल',
    disciplineQuote: 'अनुशासन प्रतिभा को हराता है। हर। दिन।',
    philosophy: 'ZNPCV दर्शन',
    newAnalysis: 'नया विश्लेषण',
    newAnalysisDesc: 'अंतिम ZNPCV चेकलिस्ट के साथ अपना पेशेवर मल्टी-टाइमफ्रेम विश्लेषण शुरू करें',
    startNow: 'अभी शुरू करें',
    dashboard: 'डैशबोर्ड',
    dashboardDesc: 'आपके विश्लेषण, प्रदर्शन ट्रैकिंग और विस्तृत आँकड़ों का अवलोकन',
    openDashboard: 'खोलें',
    marketSessions: 'बाजार सत्र',
    features: 'सुविधाएँ',
    featuresDesc: 'पेशेवर ट्रेडिंग उपकरण',
    preciseAnalysis: 'सटीक विश्लेषण',
    preciseAnalysisDesc: 'अधिकतम सटीकता के लिए W-D-4H कन्फ्लुएंस सिस्टम',
    riskManagement: 'जोखिम प्रबंधन',
    riskManagementDesc: 'एकीकृत R:R मूल्यांकन और SL/TP योजना',
    performanceTracking: 'प्रदर्शन ट्रैकिंग',
    performanceTrackingDesc: 'विस्तृत आंकड़े और सफलता दर',
    znpcvStandard: 'ZNPCV मानक',
    stepChecklist: 'चरण चेकलिस्ट',
    chartPatterns: 'चार्ट पैटर्न',
    contact: 'संपर्क',
    faqHelp: 'FAQ और सहायता',
    footerDesc: 'पेशेवर व्यापारियों के लिए अंतिम ट्रेडिंग चेकलिस्ट। अधिकतम अनुशासन और सुसंगत परिणामों के लिए विकसित।',
    riskWarning: 'ट्रेडिंग में जोखिम शामिल है। पिछले परिणाम भविष्य के लाभ की गारंटी नहीं हैं।',
    allRights: 'सर्वाधिकार सुरक्षित।',
    tradingDashboard: 'ट्रेडिंग डैशबोर्ड',
    overviewStats: 'अवलोकन और प्रदर्शन',
    totalAnalyses: 'कुल विश्लेषण',
    readyToTradeShort: 'तैयार',
    inProgress: 'प्रगति में',
    withConfluence: 'कन्फ्लुएंस के साथ',
    activity30Days: 'गतिविधि (30 दिन)',
    lastAnalyses: 'नवीनतम विश्लेषण',
    calendar: 'कैलेंडर',
    avgCompletion: 'औसत पूर्णता',
    loading: 'लोड हो रहा है...',
    noAnalyses: 'कोई विश्लेषण नहीं',
    startFirstAnalysis: 'पहला विश्लेषण शुरू करें',
    assetDirection: 'संपत्ति और दिशा',
    selectPairDirection: 'अपनी ट्रेडिंग जोड़ी और दिशा चुनें',
    goldenRules: 'ZNPCV सुनहरा नियम',
    goldenRuleText: 'कभी भी रेजिस्टेंस पर न खरीदें। कभी भी सपोर्ट पर न बेचें। एक लॉन्ग ट्रेड केवल AOI में या उसके ऊपर लिया जाता है (सपोर्ट ज़ोन)। एक शॉर्ट ट्रेड केवल AOI में या उसके नीचे लिया जाता है (रेजिस्टेंस ज़ोन)।',
    longBuyRule: 'हम AOI में या AOI के ऊपर खरीदते हैं (सपोर्ट)',
    shortSellRule: 'हम AOI में या AOI के नीचे बेचते हैं (रेजिस्टेंस)',
    neverBottomTop: 'कभी भी नीचे न बेचें! कभी भी ऊपर न खरीदें!',
    selectDirection: 'अपनी दिशा चुनें',
    buyInAoi: 'AOI में/ऊपर खरीदें',
    sellInAoi: 'AOI में/नीचे बेचें',
    weeklyAnalysis: 'साप्ताहिक विश्लेषण',
    weeklyConfirm: 'साप्ताहिक टाइमफ्रेम पुष्टि (अधिकतम 60%)',
    weeklyScore: 'साप्ताहिक स्कोर',
    weeklyTrend: 'साप्ताहिक रुझान (तेजी / मंदी)',
    atAoiRejected: 'AOI पर / अस्वीकृत',
    atAoiDesc: 'कीमत AOI पर है या कीमत AOI को अस्वीकार करती है',
    touchingEma: 'EMA को छूना / अस्वीकार करना',
    touchingEmaDesc: 'कैंडल EMA को छूती हैं या अस्वीकार करती हैं',
    candlestickRejection: 'कैंडलस्टिक अस्वीकृति',
    candlestickDesc: 'कैंडल स्पष्ट अस्वीकृति दिखाती है (Pinbar, Doji, Hammer)',
    rejectionPsp: 'PSP से अस्वीकृति',
    rejectionPspDesc: 'पिछले संरचना बिंदु से अस्वीकृति',
    roundLevel: 'गोल मनोवैज्ञानिक स्तर',
    roundLevelDesc: 'कीमत गोल संख्या पर है या उसे अस्वीकार करती है',
    swingHighLow: 'स्विंग हाई / स्विंग लो',
    swingDesc: 'कीमत स्विंग हाई या स्विंग लो पर पहुंच गई है',
    patternWeekly: 'पैटर्न (साप्ताहिक)',
    patternDesc: 'डबल टॉप/बॉटम, सामान्य/उल्टा H&S',
    dailyAnalysis: 'दैनिक विश्लेषण',
    dailyConfirm: 'दैनिक टाइमफ्रेम पुष्टि (अधिकतम 60%)',
    dailyScore: 'दैनिक स्कोर',
    dailyTrend: 'दैनिक रुझान (तेजी / मंदी)',
    h4Analysis: '4H विश्लेषण',
    h4Confirm: 'निचला टाइमफ्रेम पुष्टि (अधिकतम 35%)',
    h4Score: '4H स्कोर',
    h4Trend: '4H रुझान (तेजी / मंदी)',
    entryChecklist: 'प्रवेश चेकलिस्ट',
    entryConfirm: 'प्रवेश पुष्टि (अधिकतम 25%)',
    entryTimeframe: 'प्रवेश टाइमफ्रेम',
    entryTimeframeDesc: '30min या 1H के बीच चुनें - जो सबसे साफ संरचना और सबसे सटीक प्रवेश प्रदान करे। हम स्विंग/डे ट्रेडर्स हैं जो उच्च टाइमफ्रेम पर ध्यान केंद्रित करते हैं, स्कैल्पर्स नहीं।',
    entryScoreLabel: 'प्रवेश स्कोर',
    mssShift: 'MSS - बाजार संरचना परिवर्तन',
    mssDesc: 'संरचना का परिवर्तन / बाजार संरचना बदल गई है (30min-1hr)',
    engulfingCandle: 'एंगल्फिंग कैंडलस्टिक',
    engulfingDesc: 'पुलबैक के बाद एंगल्फिंग कैंडल दिखाई देती है (रिवर्सल पुष्टि)',
    patternIfAny: 'पैटर्न (यदि कोई है)',
    patternIfAnyDesc: 'यदि एंट्री TF पर पैटर्न दिखाई देता है',
    entryTrigger: 'एंट्री ट्रिगर प्रकार',
    pinbarRejection: 'PINBAR अस्वीकृति',
    engulfing: 'एंगल्फिंग',
    riskManagementTitle: 'जोखिम प्रबंधन',
    riskManagementSubtitle: 'पोजीशन साइज़िंग और लॉट साइज़ कैलकुलेटर',
    finalCheckTitle: 'अंतिम जांच',
    finalCheckSubtitle: 'ट्रेड से पहले अंतिम पुष्टि',
    confirmRule: 'ZNPCV नियम की पुष्टि करें',
    buyInAboveAoi: 'मैं AOI में या उसके ऊपर खरीदता हूं',
    notBuyResistance: 'मैं रेजिस्टेंस / टॉप पर नहीं खरीदता',
    sellInBelowAoi: 'मैं AOI में या उसके नीचे बेचता हूं',
    notSellSupport: 'मैं सपोर्ट / बॉटम पर नहीं बेचता',
    selectDirFirst: 'पहले पहले चरण में दिशा चुनें',
    tradeSummary: 'ट्रेड सारांश',
    notesOptional: 'नोट्स (वैकल्पिक)',
    notesPlaceholderLong: 'ट्रेड नोट्स, अवलोकन...',
    readyToTradeLabel: 'ट्रेड के लिए तैयार',
    notRecommended: 'ZNPCV ट्रेड न करने की सिफारिश करता है (न्यूनतम 85%)',
    pointsBreakdown: 'अंक विवरण',
    total: 'कुल',
    saveTrade: 'ट्रेड सहेजें',
    warningScore: 'आपका स्कोर 85% से कम है। ZNPCV मानक के अनुसार, आपको यह ट्रेड नहीं करना चाहिए।',
    doNotEnter: 'ट्रेड न करें',
    saveAnyway: 'फिर भी सहेजें',
    back: 'वापस',
    next: 'अगला',
    saving: 'सहेज रहा है...',
    direction: 'दिशा',
    long: 'लॉन्ग',
    short: 'शॉर्ट',
    of: 'का',
    dblTop: 'डबल टॉप',
    dblBtm: 'डबल बॉटम',
    hs: 'H&S',
    invHs: 'INV H&S',
    none: 'कोई नहीं',
    accountSize: 'खाता आकार',
    riskPercent: 'जोखिम %',
    entryPrice: 'प्रवेश मूल्य',
    stopLoss: 'स्टॉप लॉस',
    takeProfit: 'टेक प्रॉफिट',
    lotSizeCalc: 'लॉट साइज़ कैलकुलेटर',
    recommendedLotSize: 'अनुशंसित लॉट साइज़',
    standardLots: 'मानक लॉट',
    miniLots: 'मिनी लॉट',
    microLots: 'माइक्रो लॉट',
    units: 'यूनिट',
    riskAmount: 'जोखिम राशि $',
    slPips: 'SL पिप्स',
    tpPips: 'TP पिप्स',
    potentialProfit: 'संभावित लाभ',
    rrRatio: 'R:R अनुपात',
    quickRisk: 'त्वरित जोखिम चयन',
    lotSizeInfo: 'अपने जोखिम के आधार पर अपना सटीक लॉट साइज़ कैलकुलेट करें। अनुशंसित पोजीशन देखने के लिए एंट्री और स्टॉप लॉस दर्ज करें।',
    enterEntryAndSL: 'अपना लॉट साइज़ कैलकुलेट करने के लिए एंट्री प्राइस और स्टॉप लॉस दर्ज करें',
    minRRWarning: 'ZNPCV कम से कम 1:2.5 R:R अनुपात की सिफारिश करता है',
    goodRR: 'अच्छा जोखिम:इनाम अनुपात!',
    tradeLevels: 'ट्रेड स्तर',
    tradeHistory: 'ट्रेड इतिहास',
    performanceAnalytics: 'प्रदर्शन विश्लेषण और ट्रेड लॉग',
    allTrades: 'सभी ट्रेड',
    winLoss: 'जीत/हार',
    avgWinLoss: 'औसत जीत/हार',
    avgWin: 'औसत जीत',
    avgLoss: 'औसत हार',
    profitFactor: 'लाभ कारक',
    avgRR: 'औसत R:R',
    bestTrade: 'सर्वश्रेष्ठ ट्रेड',
    consistency: 'स्थिरता',
    trades: 'ट्रेड',
    executed: 'निष्पादित',
    pending: 'लंबित',
    confirmDelete: 'क्या आप वाकई ट्रेड हटाना चाहते हैं?',
    furtherQuestions: 'और सवाल?',
    contactUs: 'यदि आपके और प्रश्न हैं, तो कृपया हमसे संपर्क करें',
  },
  ja: {
    // 日本語 - VOLLSTÄNDIG
    online: 'オンライン',
    localTime: '現地時間',
    myAccount: 'マイアカウント',
    logout: 'ログアウト',
    login: 'ログイン',
    editProfile: 'プロフィール編集',
    save: '保存',
    ultimateChecklist: '究極のチェックリスト',
    tradingTools: '究極のトレーディングツール',
    disciplineQuote: '規律は才能に勝つ。毎日。',
    philosophy: 'ZNPCV哲学',
    newAnalysis: '新しい分析',
    newAnalysisDesc: '究極のZNPCVチェックリストでプロのマルチタイムフレーム分析を開始',
    startNow: '今すぐ始める',
    dashboard: 'ダッシュボード',
    dashboardDesc: 'あなたの分析、パフォーマンス追跡、詳細な統計の概要',
    openDashboard: '開く',
    marketSessions: '市場セッション',
    features: '機能',
    featuresDesc: 'プロフェッショナルトレーディングツール',
    preciseAnalysis: '精密分析',
    preciseAnalysisDesc: '最大精度のためのW-D-4Hコンフルエンスシステム',
    riskManagement: 'リスク管理',
    riskManagementDesc: '統合されたR:R評価とSL/TP計画',
    performanceTracking: 'パフォーマンス追跡',
    performanceTrackingDesc: '詳細な統計と成功率',
    znpcvStandard: 'ZNPCV標準',
    stepChecklist: 'ステップチェックリスト',
    chartPatterns: 'チャートパターン',
    contact: '連絡先',
    faqHelp: 'FAQとヘルプ',
    footerDesc: 'プロトレーダーのための究極のトレーディングチェックリスト。最大の規律と一貫した結果のために開発されました。',
    riskWarning: 'トレーディングにはリスクが伴います。過去の結果は将来の利益を保証するものではありません。',
    allRights: 'すべての権利を保有します。',
    tradingDashboard: 'トレーディングダッシュボード',
    overviewStats: '概要とパフォーマンス',
    totalAnalyses: '合計分析',
    readyToTradeShort: '準備完了',
    inProgress: '進行中',
    withConfluence: 'コンフルエンス付き',
    activity30Days: 'アクティビティ（30日間）',
    lastAnalyses: '最新の分析',
    calendar: 'カレンダー',
    avgCompletion: '平均完了率',
    loading: '読み込み中...',
    noAnalyses: '分析なし',
    startFirstAnalysis: '最初の分析を開始',
    assetDirection: '資産と方向',
    selectPairDirection: 'トレーディングペアと方向を選択',
    goldenRules: 'ZNPCVゴールデンルール',
    goldenRuleText: 'レジスタンスで決して買わない。サポートで決して売らない。ロングトレードはAOI内またはAOIの上でのみ実行（サポートゾーン）。ショートトレードはAOI内またはAOIの下でのみ実行（レジスタンスゾーン）。',
    longBuyRule: 'AOI内またはAOIの上で買う（サポート）',
    shortSellRule: 'AOI内またはAOIの下で売る（レジスタンス）',
    neverBottomTop: '底で売るな！天井で買うな！',
    selectDirection: '方向を選択',
    buyInAoi: 'AOI内/上で買う',
    sellInAoi: 'AOI内/下で売る',
    weeklyAnalysis: '週次分析',
    weeklyConfirm: '週次タイムフレーム確認（最大60%）',
    weeklyScore: '週次スコア',
    weeklyTrend: '週次トレンド（上昇/下降）',
    atAoiRejected: 'AOIで/拒否',
    atAoiDesc: '価格がAOIにあるまたは価格がAOIを拒否',
    touchingEma: 'EMAタッチ/拒否',
    touchingEmaDesc: 'ローソク足がEMAをタッチまたは拒否',
    candlestickRejection: 'ローソク足拒否',
    candlestickDesc: 'ローソク足が明確な拒否を示す（Pinbar、Doji、Hammer）',
    rejectionPsp: 'PSPからの拒否',
    rejectionPspDesc: '以前の構造ポイントからの拒否',
    roundLevel: 'ラウンド心理レベル',
    roundLevelDesc: '価格がラウンド数にあるまたは拒否',
    swingHighLow: 'スイングハイ/スイングロー',
    swingDesc: '価格がスイングハイまたはスイングローに到達',
    patternWeekly: 'パターン（週次）',
    patternDesc: 'ダブルトップ/ボトム、通常/逆ヘッドアンドショルダー',
    dailyAnalysis: '日次分析',
    dailyConfirm: '日次タイムフレーム確認（最大60%）',
    dailyScore: '日次スコア',
    dailyTrend: '日次トレンド（上昇/下降）',
    h4Analysis: '4H分析',
    h4Confirm: '下位タイムフレーム確認（最大35%）',
    h4Score: '4Hスコア',
    h4Trend: '4Hトレンド（上昇/下降）',
    entryChecklist: 'エントリーチェックリスト',
    entryConfirm: 'エントリー確認（最大25%）',
    entryTimeframe: 'エントリータイムフレーム',
    entryTimeframeDesc: '30分または1時間のタイムフレームを選択 - 最もクリーンな構造と最も正確なエントリーを提供するものに応じて。私たちは高いタイムフレームに焦点を当てたスイング/デイトレーダーであり、スキャルパーではありません。',
    entryScoreLabel: 'エントリースコア',
    mssShift: 'MSS - 市場構造シフト',
    mssDesc: '構造のシフト/市場構造がシフトしました（30分-1時間）',
    engulfingCandle: 'エンガルフィングキャンドル',
    engulfingDesc: 'プルバック後にエンガルフィングキャンドルが見える（反転確認）',
    patternIfAny: 'パターン（ある場合）',
    patternIfAnyDesc: 'エントリーTFでパターンが見える場合',
    entryTrigger: 'エントリートリガータイプ',
    pinbarRejection: 'Pinbar拒否',
    engulfing: 'エンガルフィング',
    riskManagementTitle: 'リスク管理',
    riskManagementSubtitle: 'ポジションサイジングとロットサイズ計算機',
    finalCheckTitle: '最終チェック',
    finalCheckSubtitle: 'トレード前の最終確認',
    confirmRule: 'ZNPCVルールを確認',
    buyInAboveAoi: 'AOI内またはAOIの上で買う',
    notBuyResistance: 'レジスタンス/天井では買わない',
    sellInBelowAoi: 'AOI内またはAOIの下で売る',
    notSellSupport: 'サポート/底では売らない',
    selectDirFirst: '最初のステップでまず方向を選択',
    tradeSummary: 'トレード要約',
    notesOptional: 'メモ（オプション）',
    notesPlaceholderLong: 'トレードメモ、観察...',
    readyToTradeLabel: 'トレード準備完了',
    notRecommended: 'ZNPCVはトレードしないことを推奨（最小85%）',
    pointsBreakdown: 'ポイント内訳',
    total: '合計',
    saveTrade: 'トレードを保存',
    warningScore: 'スコアが85%未満です。ZNPCV標準によると、このトレードに入るべきではありません。',
    doNotEnter: 'トレードに入らない',
    saveAnyway: 'とにかく保存',
    back: '戻る',
    next: '次へ',
    saving: '保存中...',
    direction: '方向',
    long: 'ロング',
    short: 'ショート',
    of: 'の',
    dblTop: 'ダブルトップ',
    dblBtm: 'ダブルボトム',
    hs: 'H&S',
    invHs: '逆H&S',
    none: 'なし',
    accountSize: '口座サイズ',
    riskPercent: 'リスク%',
    entryPrice: 'エントリー価格',
    stopLoss: 'ストップロス',
    takeProfit: 'テイクプロフィット',
    lotSizeCalc: 'ロットサイズ計算機',
    recommendedLotSize: '推奨ロットサイズ',
    standardLots: 'スタンダードロット',
    miniLots: 'ミニロット',
    microLots: 'マイクロロット',
    units: 'ユニット',
    riskAmount: 'リスク金額$',
    slPips: 'SLピップス',
    tpPips: 'TPピップス',
    potentialProfit: '潜在利益',
    rrRatio: 'R:R比率',
    quickRisk: 'クイックリスク選択',
    lotSizeInfo: 'リスクに基づいて正確なロットサイズを計算します。エントリーとストップロスを入力して推奨ポジションを表示します。',
    enterEntryAndSL: 'ロットサイズを計算するためにエントリー価格とストップロスを入力してください',
    minRRWarning: 'ZNPCVは少なくとも1:2.5のR:R比率を推奨',
    goodRR: '良いリスク:リワード比率！',
    tradeLevels: 'トレードレベル',
    tradeHistory: 'トレード履歴',
    performanceAnalytics: 'パフォーマンス分析とトレードログ',
    allTrades: '全てのトレード',
    winLoss: '勝ち/負け',
    avgWinLoss: '平均勝敗',
    avgWin: '平均利益',
    avgLoss: '平均損失',
    profitFactor: 'プロフィットファクター',
    avgRR: '平均R:R',
    bestTrade: 'ベストトレード',
    consistency: '一貫性',
    trades: 'トレード',
    executed: '実行済み',
    pending: '保留中',
    confirmDelete: '本当にトレードを削除しますか？',
    furtherQuestions: 'その他の質問？',
    contactUs: 'その他のご質問がございましたら、お気軽にお問い合わせください',
  },
  pt: {
    // Português - VOLLSTÄNDIG
    online: 'ONLINE',
    localTime: 'HORA LOCAL',
    myAccount: 'MINHA CONTA',
    logout: 'SAIR',
    login: 'ENTRAR',
    editProfile: 'EDITAR PERFIL',
    save: 'SALVAR',
    ultimateChecklist: 'CHECKLIST DEFINITIVA',
    tradingTools: 'A FERRAMENTA DEFINITIVA',
    disciplineQuote: 'Disciplina vence talento. Todos. Os. Dias.',
    philosophy: 'FILOSOFIA ZNPCV',
    newAnalysis: 'NOVA ANÁLISE',
    newAnalysisDesc: 'Comece sua análise profissional multi-timeframe com o checklist definitivo ZNPCV',
    startNow: 'Começar agora',
    dashboard: 'PAINEL',
    dashboardDesc: 'Visão geral de suas análises, rastreamento de desempenho e estatísticas detalhadas',
    openDashboard: 'Abrir',
    marketSessions: 'SESSÕES DE MERCADO',
    features: 'RECURSOS',
    featuresDesc: 'Ferramentas de Trading Profissionais',
    preciseAnalysis: 'ANÁLISE PRECISA',
    preciseAnalysisDesc: 'Sistema de Confluência W-D-4H para máxima precisão',
    riskManagement: 'GESTÃO DE RISCO',
    riskManagementDesc: 'Avaliação integrada R:R e planejamento SL/TP',
    performanceTracking: 'RASTREAMENTO DE DESEMPENHO',
    performanceTrackingDesc: 'Estatísticas detalhadas e taxas de sucesso',
    znpcvStandard: 'PADRÃO ZNPCV',
    stepChecklist: 'CHECKLIST DE PASSOS',
    chartPatterns: 'PADRÕES DE GRÁFICO',
    contact: 'CONTATO',
    faqHelp: 'FAQ E AJUDA',
    footerDesc: 'O checklist de trading definitivo para traders profissionais. Desenvolvido para máxima disciplina e resultados consistentes.',
    riskWarning: 'Trading envolve riscos. Resultados passados não garantem lucros futuros.',
    allRights: 'Todos os direitos reservados.',
    tradingDashboard: 'PAINEL DE TRADING',
    overviewStats: 'VISÃO GERAL E DESEMPENHO',
    totalAnalyses: 'ANÁLISES TOTAIS',
    readyToTradeShort: 'PRONTO',
    inProgress: 'EM ANDAMENTO',
    withConfluence: 'COM CONFLUÊNCIA',
    activity30Days: 'ATIVIDADE (30 DIAS)',
    lastAnalyses: 'ÚLTIMAS ANÁLISES',
    calendar: 'CALENDÁRIO',
    avgCompletion: 'CONCLUSÃO MÉDIA',
    loading: 'CARREGANDO...',
    noAnalyses: 'SEM ANÁLISES',
    startFirstAnalysis: 'INICIAR PRIMEIRA ANÁLISE',
    assetDirection: 'ATIVO E DIREÇÃO',
    selectPairDirection: 'Selecione seu par de trading e direção',
    goldenRules: 'REGRA DE OURO ZNPCV',
    goldenRuleText: 'Nunca comprar na resistência. Nunca vender no suporte. Um trade LONG só é executado no ou acima do AOI (zona de suporte). Um trade SHORT só é executado no ou abaixo do AOI (zona de resistência).',
    longBuyRule: 'Compramos NO AOI ou ACIMA do AOI (Suporte)',
    shortSellRule: 'Vendemos NO AOI ou ABAIXO do AOI (Resistência)',
    neverBottomTop: 'NUNCA VENDA NO FUNDO! NUNCA COMPRE NO TOPO!',
    selectDirection: 'SELECIONE SUA DIREÇÃO',
    buyInAoi: 'Comprar no/acima AOI',
    sellInAoi: 'Vender no/abaixo AOI',
    weeklyAnalysis: 'ANÁLISE SEMANAL',
    weeklyConfirm: 'Confirmações de Timeframe Semanal (máx 60%)',
    weeklyScore: 'PONTUAÇÃO SEMANAL',
    weeklyTrend: 'TENDÊNCIA SEMANAL (ALTA / BAIXA)',
    atAoiRejected: 'NO AOI / REJEITADO',
    atAoiDesc: 'Preço está no AOI OU Preço rejeita AOI',
    touchingEma: 'TOCANDO / REJEITANDO EMA',
    touchingEmaDesc: 'Velas tocam OU rejeitam o EMA',
    candlestickRejection: 'REJEIÇÃO DE VELA',
    candlestickDesc: 'Vela mostra rejeição clara (Pinbar, Doji, Hammer)',
    rejectionPsp: 'REJEIÇÃO DO PSP',
    rejectionPspDesc: 'Rejeição do Ponto de Estrutura Anterior',
    roundLevel: 'NÍVEL PSICOLÓGICO REDONDO',
    roundLevelDesc: 'Preço está em OU rejeita número redondo',
    swingHighLow: 'SWING ALTO / SWING BAIXO',
    swingDesc: 'Preço alcançou Swing Alto OU Swing Baixo',
    patternWeekly: 'PADRÃO (SEMANAL)',
    patternDesc: 'Topo/Fundo Duplo, Ombro-Cabeça-Ombro Normal/Invertido',
    dailyAnalysis: 'ANÁLISE DIÁRIA',
    dailyConfirm: 'Confirmações de Timeframe Diário (máx 60%)',
    dailyScore: 'PONTUAÇÃO DIÁRIA',
    dailyTrend: 'TENDÊNCIA DIÁRIA (ALTA / BAIXA)',
    h4Analysis: 'ANÁLISE 4H',
    h4Confirm: 'Confirmação de Timeframe Inferior (máx 35%)',
    h4Score: 'PONTUAÇÃO 4H',
    h4Trend: 'TENDÊNCIA 4H (ALTA / BAIXA)',
    entryChecklist: 'CHECKLIST DE ENTRADA',
    entryConfirm: 'Confirmações de Entrada (máx 25%)',
    entryTimeframe: 'TIMEFRAME DE ENTRADA',
    entryTimeframeDesc: 'Escolha entre 30min ou 1H - dependendo de qual fornece a estrutura mais limpa e a entrada mais precisa. Somos traders Swing/Day focados em timeframes superiores, não scalpers.',
    entryScoreLabel: 'PONTUAÇÃO DE ENTRADA',
    mssShift: 'MSS - MUDANÇA DE ESTRUTURA DE MERCADO',
    mssDesc: 'Mudança de Estrutura / Estrutura do mercado mudou (30min-1hr)',
    engulfingCandle: 'VELA ENGOLINDO',
    engulfingDesc: 'Vela engolindo visível após pullback (Confirmação de Reversão)',
    patternIfAny: 'PADRÃO (SE HOUVER)',
    patternIfAnyDesc: 'Se um padrão é visível no TF de Entrada',
    entryTrigger: 'TIPO DE GATILHO DE ENTRADA',
    pinbarRejection: 'REJEIÇÃO PINBAR',
    engulfing: 'ENGOLINDO',
    riskManagementTitle: 'GESTÃO DE RISCO',
    riskManagementSubtitle: 'Dimensionamento de Posição e Calculadora de Lote',
    finalCheckTitle: 'VERIFICAÇÃO FINAL',
    finalCheckSubtitle: 'Confirmação final antes do trade',
    confirmRule: 'CONFIRME A REGRA ZNPCV',
    buyInAboveAoi: 'COMPRO NO OU ACIMA DO AOI',
    notBuyResistance: 'NÃO compro na resistência / topo',
    sellInBelowAoi: 'VENDO NO OU ABAIXO DO AOI',
    notSellSupport: 'NÃO vendo no suporte / fundo',
    selectDirFirst: 'Selecione uma direção no primeiro passo primeiro',
    tradeSummary: 'RESUMO DO TRADE',
    notesOptional: 'NOTAS (OPCIONAL)',
    notesPlaceholderLong: 'Notas do trade, observações...',
    readyToTradeLabel: 'PRONTO PARA NEGOCIAR',
    notRecommended: 'ZNPCV recomenda NÃO negociar (mín. 85%)',
    pointsBreakdown: 'DETALHAMENTO DE PONTOS',
    total: 'TOTAL',
    saveTrade: 'SALVAR TRADE',
    warningScore: 'Sua pontuação está abaixo de 85%. De acordo com o padrão ZNPCV, você NÃO deve entrar neste trade.',
    doNotEnter: 'NÃO ENTRAR NO TRADE',
    saveAnyway: 'Salvar mesmo assim',
    back: 'VOLTAR',
    next: 'PRÓXIMO',
    saving: 'SALVANDO...',
    direction: 'DIREÇÃO',
    long: 'LONG',
    short: 'SHORT',
    of: 'DE',
    dblTop: 'TOPO DUPLO',
    dblBtm: 'FUNDO DUPLO',
    hs: 'OCO',
    invHs: 'OCO INV',
    none: 'NENHUM',
    accountSize: 'TAMANHO DA CONTA',
    riskPercent: 'RISCO %',
    entryPrice: 'PREÇO DE ENTRADA',
    stopLoss: 'STOP LOSS',
    takeProfit: 'TAKE PROFIT',
    lotSizeCalc: 'CALCULADORA DE LOTE',
    recommendedLotSize: 'TAMANHO DE LOTE RECOMENDADO',
    standardLots: 'Lotes Padrão',
    miniLots: 'MINI LOTES',
    microLots: 'MICRO LOTES',
    units: 'UNIDADES',
    riskAmount: 'RISCO $',
    slPips: 'PIPS SL',
    tpPips: 'PIPS TP',
    potentialProfit: 'LUCRO POTENCIAL',
    rrRatio: 'RELAÇÃO R:R',
    quickRisk: 'SELEÇÃO RÁPIDA DE RISCO',
    lotSizeInfo: 'Calcule seu tamanho de lote exato com base no seu risco. Insira Entrada e Stop Loss para ver a posição recomendada.',
    enterEntryAndSL: 'Insira Preço de Entrada e Stop Loss para calcular seu Tamanho de Lote',
    minRRWarning: 'ZNPCV recomenda pelo menos relação 1:2.5 R:R',
    goodRR: 'Boa relação Risco:Recompensa!',
    tradeLevels: 'NÍVEIS DE TRADE',
    tradeHistory: 'HISTÓRICO DE TRADES',
    performanceAnalytics: 'Análise de Performance e Registro de Trades',
    allTrades: 'TODOS OS TRADES',
    winLoss: 'VITÓRIAS/DERROTAS',
    avgWinLoss: 'MÉDIA WIN/LOSS',
    avgWin: 'MÉDIA DE GANHO',
    avgLoss: 'MÉDIA DE PERDA',
    profitFactor: 'FATOR DE LUCRO',
    avgRR: 'R:R MÉDIO',
    bestTrade: 'MELHOR TRADE',
    consistency: 'CONSISTÊNCIA',
    trades: 'TRADES',
    executed: 'EXECUTADOS',
    pending: 'PENDENTE',
    confirmDelete: 'Realmente excluir o trade?',
    furtherQuestions: 'MAIS PERGUNTAS?',
    contactUs: 'Se você tiver mais perguntas, entre em contato conosco diretamente',
  },
  ar: {
    // العربية - VOLLSTÄNDIG
    online: 'متصل',
    localTime: 'الوقت المحلي',
    myAccount: 'حسابي',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    editProfile: 'تعديل الملف الشخصي',
    save: 'حفظ',
    ultimateChecklist: 'القائمة النهائية',
    tradingTools: 'الأداة النهائية للتداول',
    disciplineQuote: 'الانضباط يتفوق على الموهبة. كل. يوم.',
    philosophy: 'فلسفة ZNPCV',
    newAnalysis: 'تحليل جديد',
    newAnalysisDesc: 'ابدأ تحليلك الاحترافي متعدد الأطر الزمنية مع قائمة ZNPCV النهائية',
    startNow: 'ابدأ الآن',
    dashboard: 'لوحة التحكم',
    dashboardDesc: 'نظرة عامة على تحليلاتك، تتبع الأداء والإحصائيات التفصيلية',
    openDashboard: 'فتح',
    marketSessions: 'جلسات السوق',
    features: 'الميزات',
    featuresDesc: 'أدوات التداول المهنية',
    preciseAnalysis: 'تحليل دقيق',
    preciseAnalysisDesc: 'نظام التقارب W-D-4H لأقصى دقة',
    riskManagement: 'إدارة المخاطر',
    riskManagementDesc: 'تقييم R:R المتكامل وتخطيط SL/TP',
    performanceTracking: 'تتبع الأداء',
    performanceTrackingDesc: 'إحصائيات مفصلة ومعدلات نجاح',
    znpcvStandard: 'معيار ZNPCV',
    stepChecklist: 'قائمة الخطوات',
    chartPatterns: 'أنماط الرسم البياني',
    contact: 'اتصل',
    faqHelp: 'الأسئلة الشائعة والمساعدة',
    footerDesc: 'قائمة التداول النهائية للمتداولين المحترفين. مطورة لأقصى انضباط ونتائج متسقة.',
    riskWarning: 'التداول ينطوي على مخاطر. النتائج السابقة لا تضمن الأرباح المستقبلية.',
    allRights: 'جميع الحقوق محفوظة.',
    tradingDashboard: 'لوحة تحكم التداول',
    overviewStats: 'نظرة عامة والأداء',
    totalAnalyses: 'إجمالي التحليلات',
    readyToTradeShort: 'جاهز',
    inProgress: 'قيد التنفيذ',
    withConfluence: 'مع التقارب',
    activity30Days: 'النشاط (30 يومًا)',
    lastAnalyses: 'أحدث التحليلات',
    calendar: 'التقويم',
    avgCompletion: 'متوسط الإكمال',
    loading: 'جاري التحميل...',
    noAnalyses: 'لا توجد تحليلات',
    startFirstAnalysis: 'ابدأ التحليل الأول',
    assetDirection: 'الأصل والاتجاه',
    selectPairDirection: 'اختر زوج التداول والاتجاه',
    goldenRules: 'القاعدة الذهبية ZNPCV',
    goldenRuleText: 'لا تشترِ أبدًا عند المقاومة. لا تبع أبدًا عند الدعم. صفقة الشراء تُنفذ فقط في أو فوق AOI (منطقة الدعم). صفقة البيع تُنفذ فقط في أو تحت AOI (منطقة المقاومة).',
    longBuyRule: 'نشتري في أو فوق AOI (الدعم)',
    shortSellRule: 'نبيع في أو تحت AOI (المقاومة)',
    neverBottomTop: 'لا تبع أبدًا في القاع! لا تشتري أبدًا في القمة!',
    selectDirection: 'اختر اتجاهك',
    buyInAoi: 'شراء في/فوق AOI',
    sellInAoi: 'بيع في/تحت AOI',
    weeklyAnalysis: 'تحليل أسبوعي',
    weeklyConfirm: 'تأكيدات الإطار الزمني الأسبوعي (الحد الأقصى 60٪)',
    weeklyScore: 'النقاط الأسبوعية',
    weeklyTrend: 'الاتجاه الأسبوعي (صاعد / هابط)',
    atAoiRejected: 'عند AOI / مرفوض',
    atAoiDesc: 'السعر عند AOI أو السعر يرفض AOI',
    touchingEma: 'لمس / رفض EMA',
    touchingEmaDesc: 'الشموع تلمس أو ترفض EMA',
    candlestickRejection: 'رفض الشمعة',
    candlestickDesc: 'الشمعة تظهر رفضًا واضحًا (Pinbar، Doji، Hammer)',
    rejectionPsp: 'الرفض من PSP',
    rejectionPspDesc: 'الرفض من نقطة الهيكل السابقة',
    roundLevel: 'مستوى نفسي دائري',
    roundLevelDesc: 'السعر عند أو يرفض رقم دائري',
    swingHighLow: 'قمة التأرجح / قاع التأرجح',
    swingDesc: 'وصل السعر إلى قمة التأرجح أو قاع التأرجح',
    patternWeekly: 'نمط (أسبوعي)',
    patternDesc: 'قمة/قاع مزدوج، رأس وكتفين عادي/معكوس',
    dailyAnalysis: 'تحليل يومي',
    dailyConfirm: 'تأكيدات الإطار الزمني اليومي (الحد الأقصى 60٪)',
    dailyScore: 'النقاط اليومية',
    dailyTrend: 'الاتجاه اليومي (صاعد / هابط)',
    h4Analysis: 'تحليل 4 ساعات',
    h4Confirm: 'تأكيد الإطار الزمني الأدنى (الحد الأقصى 35٪)',
    h4Score: 'نقاط 4 ساعات',
    h4Trend: 'اتجاه 4 ساعات (صاعد / هابط)',
    entryChecklist: 'قائمة الدخول',
    entryConfirm: 'تأكيدات الدخول (الحد الأقصى 25٪)',
    entryTimeframe: 'إطار زمني للدخول',
    entryTimeframeDesc: 'اختر بين 30 دقيقة أو ساعة واحدة - حسب أيهما يوفر أنظف هيكل وأدق دخول. نحن متداولون متأرجحون/يوميون نركز على أطر زمنية أعلى، لسنا متداولين سريعين.',
    entryScoreLabel: 'نقاط الدخول',
    mssShift: 'MSS - تحول هيكل السوق',
    mssDesc: 'تحول الهيكل / تحول هيكل السوق (30min-1hr)',
    engulfingCandle: 'شمعة ابتلاعية',
    engulfingDesc: 'شمعة ابتلاعية مرئية بعد التراجع (تأكيد الانعكاس)',
    patternIfAny: 'نمط (إذا كان هناك واحد)',
    patternIfAnyDesc: 'إذا كان النمط مرئيًا على إطار الدخول الزمني',
    entryTrigger: 'نوع محفز الدخول',
    pinbarRejection: 'رفض PINBAR',
    engulfing: 'ابتلاعي',
    riskManagementTitle: 'إدارة المخاطر',
    riskManagementSubtitle: 'تحجيم الموقف وحاسبة حجم اللوت',
    finalCheckTitle: 'الفحص النهائي',
    finalCheckSubtitle: 'التأكيد النهائي قبل التداول',
    confirmRule: 'أكد قاعدة ZNPCV',
    buyInAboveAoi: 'أشتري في أو فوق AOI',
    notBuyResistance: 'لا أشتري عند المقاومة / القمة',
    sellInBelowAoi: 'أبيع في أو تحت AOI',
    notSellSupport: 'لا أبيع عند الدعم / القاع',
    selectDirFirst: 'اختر الاتجاه في الخطوة الأولى أولاً',
    tradeSummary: 'ملخص الصفقة',
    notesOptional: 'ملاحظات (اختياري)',
    notesPlaceholderLong: 'ملاحظات الصفقة، الملاحظات...',
    readyToTradeLabel: 'جاهز للتداول',
    notRecommended: 'يوصي ZNPCV بعدم التداول (الحد الأدنى 85٪)',
    pointsBreakdown: 'تفصيل النقاط',
    total: 'الإجمالي',
    saveTrade: 'حفظ الصفقة',
    warningScore: 'درجتك أقل من 85٪. وفقًا لمعيار ZNPCV، يجب ألا تدخل هذه الصفقة.',
    doNotEnter: 'لا تدخل الصفقة',
    saveAnyway: 'احفظ على أي حال',
    back: 'رجوع',
    next: 'التالي',
    saving: 'جاري الحفظ...',
    direction: 'الاتجاه',
    long: 'شراء',
    short: 'بيع',
    of: 'من',
    dblTop: 'قمة مزدوجة',
    dblBtm: 'قاع مزدوج',
    hs: 'رأس وكتفين',
    invHs: 'رأس وكتفين معكوس',
    none: 'لا شيء',
    accountSize: 'حجم الحساب',
    riskPercent: 'المخاطرة %',
    entryPrice: 'سعر الدخول',
    stopLoss: 'وقف الخسارة',
    takeProfit: 'جني الأرباح',
    lotSizeCalc: 'حاسبة حجم اللوت',
    recommendedLotSize: 'حجم اللوت الموصى به',
    standardLots: 'لوت قياسي',
    miniLots: 'ميني لوت',
    microLots: 'ميكرو لوت',
    units: 'وحدات',
    riskAmount: 'مبلغ المخاطرة $',
    slPips: 'نقاط SL',
    tpPips: 'نقاط TP',
    potentialProfit: 'الربح المحتمل',
    rrRatio: 'نسبة R:R',
    quickRisk: 'اختيار المخاطرة السريع',
    lotSizeInfo: 'احسب حجم اللوت الدقيق الخاص بك بناءً على مخاطرتك. أدخل الدخول ووقف الخسارة لرؤية الموقف الموصى به.',
    enterEntryAndSL: 'أدخل سعر الدخول ووقف الخسارة لحساب حجم اللوت الخاص بك',
    minRRWarning: 'يوصي ZNPCV بنسبة R:R على الأقل 1:2.5',
    goodRR: 'نسبة مخاطرة:مكافأة جيدة!',
    tradeLevels: 'مستويات الصفقة',
    tradeHistory: 'سجل الصفقات',
    performanceAnalytics: 'تحليل الأداء وسجل الصفقات',
    allTrades: 'جميع الصفقات',
    winLoss: 'ربح/خسارة',
    avgWinLoss: 'متوسط الربح/الخسارة',
    avgWin: 'متوسط الربح',
    avgLoss: 'متوسط الخسارة',
    profitFactor: 'عامل الربح',
    avgRR: 'متوسط R:R',
    bestTrade: 'أفضل صفقة',
    consistency: 'الاتساق',
    trades: 'صفقات',
    executed: 'منفذة',
    pending: 'معلقة',
    confirmDelete: 'هل تريد حقًا حذف الصفقة؟',
    furtherQuestions: 'المزيد من الأسئلة؟',
    contactUs: 'إذا كان لديك المزيد من الأسئلة، اتصل بنا مباشرة',
  },
  de: {
    // Header
    online: 'ONLINE',
    localTime: 'ORTSZEIT',
    myAccount: 'MEIN ACCOUNT',
    logout: 'AUSLOGGEN',
    login: 'ANMELDEN',
    editProfile: 'PROFIL BEARBEITEN',
    save: 'SPEICHERN',
    
    // Home
    ultimateChecklist: 'ULTIMATIVE CHECKLISTE',
    heroSubtitle: 'Die ultimative Trading-Checkliste die es je gegeben hat.',
    heroDesc: 'Professionelle Multi-Timeframe Analyse • Strukturierte Entscheidungsfindung • Maximale Disziplin',
    newAnalysis: 'NEUE ANALYSE',
    newAnalysisDesc: 'Starte deine professionelle Multi-Timeframe Analyse mit der ultimativen ZNPCV Checkliste',
    startNow: 'Jetzt starten',
    dashboard: 'ÜBERSICHT',
    dashboardDesc: 'Übersicht deiner Analysen, Leistungsverfolgung und detaillierte Statistiken',
    openDashboard: 'Öffnen',
    
    // Market Sessions
    marketSessions: 'HANDELSSITZUNGEN',
    open: 'OFFEN',
    closed: 'GESCHLOSSEN',
    
    // Assets
    forex: 'DEVISEN',
    crypto: 'KRYPTO',
    stocks: 'AKTIEN',
    commodities: 'ROHSTOFFE',
    indices: 'INDIZES',
    
    // Features
    preciseAnalysis: 'PRÄZISE ANALYSE',
    preciseAnalysisDesc: 'W-D-4H Übereinstimmungssystem für maximale Genauigkeit',
    riskManagement: 'RISIKOMANAGEMENT',
    riskManagementDesc: 'Integrierte R:R Bewertung und SL/TP Planung',
    performanceTracking: 'LEISTUNGSVERFOLGUNG',
    performanceTrackingDesc: 'Detaillierte Statistiken und Erfolgsquoten',
    
    // Footer
    sslEncrypted: 'SSL VERSCHLÜSSELT',
    gdprCompliant: 'DSGVO KONFORM',
    dataProtection: 'DATENSCHUTZ',
    worldwide: 'WELTWEIT VERFÜGBAR',
    contact: 'KONTAKT',
    faqHelp: 'FAQ & HILFE',
    footerDesc: 'Die ultimative Trading-Checkliste für professionelle Trader. Entwickelt für maximale Disziplin und beständige Ergebnisse.',
    riskWarning: 'Trading birgt Risiken. Vergangene Ergebnisse sind keine Garantie für zukünftige Gewinne.',
    allRights: 'Alle Rechte vorbehalten.',
    
    // Checklist
    selectAsset: 'WÄHRUNGSPAAR',
    selectAssetDesc: 'WELCHES PAAR WILLST DU HANDELN?',
    trendAnalysis: 'TRENDANALYSE',
    trendAnalysisDesc: 'PRÜFE ALLE 3 ZEITRAHMEN',
    weekly: 'WÖCHENTLICH',
    daily: 'TÄGLICH',
    fourHour: '4 STUNDEN',
    mainTrend: 'Haupttrend',
    midTerm: 'Mittelfristig',
    shortTerm: 'Kurzfristig',
    bullish: 'BULLISH',
    bearish: 'BEARISH',
    confluence: 'ÜBEREINSTIMMUNG',
    noConfluence: 'KEINE ÜBEREINSTIMMUNG',
    allTimeframes: 'Alle Zeitrahmen zeigen',
    dailyH4Sync: 'TÄGLICH & 4H SYNCHRON',
    higherProbability: 'Höhere Wahrscheinlichkeit für erfolgreichen Trade!',
    confluenceTooltip: 'Übereinstimmung bedeutet, dass alle Zeitrahmen (Wöchentlich, Täglich, 4H) in die gleiche Richtung zeigen. Das erhöht die Erfolgswahrscheinlichkeit.',
    
    // AOI
    aoi: 'INTERESSENSBEREICH',
    aoiDesc: 'AOI ZONE PRÜFEN',
    aoiDrawn: 'AOI EINGEZEICHNET',
    aoiDrawnDesc: 'Hast du deinen Interessensbereich im Chart markiert?',
    priceInAoi: 'PREIS IM AOI',
    priceInAoiDesc: 'Ist der aktuelle Preis in deiner AOI Zone?',
    pricePosition: 'PREISPOSITION ZUM AOI',
    aboveAoi: 'ÜBER AOI',
    belowAoi: 'UNTER AOI',
    shortSetup: '= VERKAUF Setup',
    longSetup: '= KAUF Setup',
    
    // Structure
    structureCheck: 'STRUKTURPRÜFUNG',
    structureCheckDesc: 'PSS & EMA PRÜFEN',
    pssRejected: 'PSS ABGELEHNT',
    pssRejectedDesc: 'Vorherige Struktur (Support/Widerstand) wurde respektiert und abgelehnt',
    emaRespected: 'EMA RESPEKTIERT',
    emaRespectedDesc: 'Der Preis hat den gleitenden Durchschnitt respektiert',
    structureConfirmed: 'STRUKTUR BESTÄTIGT',
    
    // Patterns
    patterns: 'CHARTMUSTER',
    patternsDesc: 'NUR UNSERE MUSTER',
    headShoulders: 'KOPF-SCHULTER',
    invHeadShoulders: 'UMGEKEHRTE KOPF-SCHULTER',
    doubleTop: 'DOPPELHOCH',
    doubleBottom: 'DOPPELTIEF',
    patternIdentified: 'MUSTER ERKANNT',
    patternIdentifiedDesc: 'Eines unserer 4 Muster ist im Chart sichtbar',
    patternConfirmed: 'MUSTER BESTÄTIGT',
    patternConfirmedDesc: 'Das Muster ist vollständig und gültig',
    
    // Entry
    entryConfirmation: 'EINSTIEGSBESTÄTIGUNG',
    entryConfirmationDesc: 'MSS & ENGULFING (30MIN - 1STD)',
    mssConfirmed: 'MSS / SOS BESTÄTIGT',
    mssConfirmedDesc: 'Marktstrukturwechsel - Preis hat gedreht (Bullish → Bearish oder umgekehrt)',
    engulfingAfterPullback: 'ENGULFING NACH RÜCKSETZER',
    engulfingQuestion: 'Wird die Kerze nach dem Rücksetzer verschlungen?',
    blueEngulfing: 'BLAUE ENGULFING',
    redEngulfing: 'ROTE ENGULFING',
    longEntry: '= KAUF Einstieg',
    shortEntry: '= VERKAUF Einstieg',
    noEngulfing: 'KEINE ENGULFING',
    entrySignalConfirmed: 'EINSTIEGSSIGNAL BESTÄTIGT',
    
    // Final
    finalCheck: 'ABSCHLUSSPRÜFUNG',
    finalCheckDesc: 'WICHTIGE REGELN',
    importantRules: 'WICHTIGE REGELN',
    notBuyingResistance: 'NICHT BEIM WIDERSTAND KAUFEN',
    notBuyingResistanceDesc: 'Ich kaufe NICHT beim Widerstand',
    notSellingSupport: 'NICHT BEI UNTERSTÜTZUNG VERKAUFEN',
    notSellingSupportDesc: 'Ich verkaufe NICHT bei der Unterstützung',
    summary: 'ZUSAMMENFASSUNG',
    pair: 'PAAR',
    trend: 'TREND',
    mixed: 'GEMISCHT',
    inAoi: 'IM AOI',
    entry: 'EINSTIEG',
    notes: 'NOTIZEN',
    notesPlaceholder: 'Trade Notizen...',
    readyToTrade: 'BEREIT ZUM HANDELN',
    allConfirmed: 'Alle Bestätigungen erfüllt!',
    
    // Navigation
    back: 'ZURÜCK',
    next: 'WEITER',
    save: 'SPEICHERN',
    saving: 'SPEICHERN...',
    loading: 'LADEN...',
    
    // Dashboard
    tradingDashboard: 'HANDELSÜBERSICHT',
    overviewStats: 'ÜBERSICHT & LEISTUNG',
    totalAnalyses: 'ANALYSEN GESAMT',
    readyToTradeShort: 'BEREIT',
    inProgress: 'IN BEARBEITUNG',
    withConfluence: 'MIT ÜBEREINSTIMMUNG',
    activity30Days: 'AKTIVITÄT (30 TAGE)',
    lastAnalyses: 'LETZTE ANALYSEN',
    of: 'VON',
    noAnalyses: 'KEINE ANALYSEN',
    startFirstAnalysis: 'ERSTE ANALYSE STARTEN',
    direction: 'RICHTUNG',
    long: 'KAUF',
    short: 'VERKAUF',
    calendar: 'KALENDER',
    avgCompletion: 'DURCHSCHNITTLICHER FORTSCHRITT',
    
    // Quotes
    quote1: '"Plane deinen Trade, handle deinen Plan."',
    quote2: '"Disziplin entscheidet über Erfolg oder Misserfolg."',
    quote3: '"Wir kaufen nicht beim Widerstand, wir verkaufen nicht bei Unterstützung."',
    quote4: '"Geduld ist der Schlüssel zum Erfolg im Trading."',
    quote5: '"Risikomanagement ist wichtiger als Gewinnmaximierung."',
    
    // Warning
    warningTitle: 'WARNUNG - KEIN A+++ TRADE',
    warningDesc: 'Deine Checkliste ist unter 85%. Nach ZNPCV Standard solltest du nur A+++ Trades eingehen. Überprüfe alle Kriterien erneut oder überspringe diesen Trade.',
    warningButton: 'TRADE NICHT EINGEHEN',
    proceedAnyway: 'Trotzdem fortfahren',
    aPlusTradeOnly: 'NUR A+++ TRADES',
    
    // Additional translations
    features: 'FUNKTIONEN',
    featuresDesc: 'Professionelle Trading-Werkzeuge',
    znpcvStandard: 'ZNPCV STANDARD',
    stepChecklist: 'SCHRITT CHECKLISTE',
    chartPatterns: 'CHART MUSTER',
    tradingTools: 'DAS ULTIMATIVE TRADING-TOOL',
    philosophy: 'ZNPCV PHILOSOPHIE',
    disciplineQuote: 'Disziplin schlägt Talent. Jeden. Einzelnen. Tag.',
    
    // Risk Management
    accountSize: 'KONTOGRÖSSE',
    riskPercent: 'RISIKO %',
    entryPrice: 'EINSTIEGSPREIS',
    stopLoss: 'STOP LOSS',
    takeProfit: 'TAKE PROFIT',
    lotSizeCalc: 'LOT SIZE RECHNER',
    recommendedLotSize: 'EMPFOHLENE LOT SIZE',
    standardLots: 'Standard Lots',
    miniLots: 'MINI LOTS',
    microLots: 'MICRO LOTS',
    units: 'EINHEITEN',
    riskAmount: 'RISIKO $',
    slPips: 'SL PIPS',
    tpPips: 'TP PIPS',
    potentialProfit: 'POTENZIELLER GEWINN',
    rrRatio: 'R:R VERHÄLTNIS',
    quickRisk: 'SCHNELLE RISIKO-AUSWAHL',
    lotSizeInfo: 'Berechne deine exakte Lot Size basierend auf deinem Risiko. Gib Entry & Stop Loss ein, um die empfohlene Position zu sehen.',
    enterEntryAndSL: 'Gib Entry Preis und Stop Loss ein, um deine Lot Size zu berechnen',
    minRRWarning: 'ZNPCV empfiehlt mindestens 1:2.5 R:R Verhältnis',
    goodRR: 'Gutes Risk:Reward Verhältnis!',
    tradeLevels: 'TRADE LEVELS',
    
    // Checklist specific
    assetDirection: 'ASSET & RICHTUNG',
    selectPairDirection: 'Wähle dein Handelspaar und die Trade-Richtung',
    goldenRules: 'ZNPCV REGEL',
    goldenRuleText: 'Nicht am Widerstand kaufen • Nicht am Support verkaufen',
    longBuyRule: 'Wir kaufen IM AOI oder ÜBER dem AOI (Support)',
    shortSellRule: 'Wir verkaufen IM AOI oder UNTER dem AOI (Resistance)',
    neverBottomTop: 'NIE AM BODEN VERKAUFEN! NIE AM TOP KAUFEN!',
    selectDirection: 'WÄHLE DEINE RICHTUNG',
    buyInAoi: 'Kaufen im/über AOI',
    sellInAoi: 'Verkaufen im/unter AOI',
    weeklyAnalysis: 'WEEKLY ANALYSE',
    weeklyConfirm: 'Weekly Timeframe Confirmations (max 60%)',
    weeklyScore: 'WEEKLY SCORE',
    weeklyTrend: 'WEEKLY TREND (BULLISH / BEARISH)',
    atAoiRejected: 'AT AOI / REJECTED',
    atAoiDesc: 'Preis ist am AOI ODER Preis lehnt AOI ab',
    touchingEma: 'TOUCHING / REJECTING EMA',
    touchingEmaDesc: 'Kerzen berühren ODER lehnen den EMA ab',
    candlestickRejection: 'CANDLESTICK REJECTION',
    candlestickDesc: 'Kerze zeigt klare Ablehnung (Pinbar, Doji, Hammer)',
    rejectionPsp: 'REJECTION FROM PSP',
    rejectionPspDesc: 'Ablehnung vom Previous Structure Point',
    roundLevel: 'ROUND PSYCH LEVEL',
    roundLevelDesc: 'Preis ist an ODER lehnt runde Zahl ab',
    swingHighLow: 'SWING HIGH / SWING LOW',
    swingDesc: 'Preis ist bei Swing High ODER Swing Low angekommen',
    patternWeekly: 'PATTERN (WEEKLY)',
    patternDesc: 'Double Top/Bottom, Normal/Inverted H&S',
    dailyAnalysis: 'DAILY ANALYSE',
    dailyConfirm: 'Daily Timeframe Confirmations (max 60%)',
    dailyScore: 'DAILY SCORE',
    dailyTrend: 'DAILY TREND (BULLISH / BEARISH)',
    h4Analysis: '4H ANALYSE',
    h4Confirm: 'Lower Timeframe Confirmation (max 35%)',
    h4Score: '4H SCORE',
    h4Trend: '4H TREND (BULLISH / BEARISH)',
    entryChecklist: 'ENTRY CHECKLIST',
    entryConfirm: 'Entry Confirmations (max 25%)',
    entryTimeframe: 'ENTRY TIMEFRAME',
    entryTimeframeDesc: 'Wähle zwischen 30min oder 1H - je nach sauberster Struktur und präzisestem Entry (Swing/Day Trading)',
    entryScoreLabel: 'ENTRY SCORE',
    mssShift: 'MSS - MARKET STRUCTURE SHIFT',
    mssDesc: 'Shift of Structure / Marktstruktur hat gewechselt (30min-1hr)',
    engulfingCandle: 'ENGULFING CANDLESTICK',
    engulfingDesc: 'Engulfing Kerze nach Pullback sichtbar (Reversal Confirmation)',
    patternIfAny: 'PATTERN (IF THERE IS ONE)',
    patternIfAnyDesc: 'Falls ein Pattern auf Entry TF sichtbar ist',
    entryTrigger: 'ENTRY TRIGGER TYP',
    pinbarRejection: 'PINBAR REJECTION',
    engulfing: 'ENGULFING',
    riskManagementTitle: 'RISK MANAGEMENT',
    riskManagementSubtitle: 'Position Sizing & Lot Size Calculator',
    finalCheckTitle: 'FINAL CHECK',
    finalCheckSubtitle: 'Letzte Bestätigung vor dem Trade',
    confirmRule: 'BESTÄTIGE DIE ZNPCV REGEL',
    buyInAboveAoi: 'ICH KAUFE IM ODER ÜBER DEM AOI',
    notBuyResistance: 'Ich kaufe NICHT am Widerstand / Top',
    sellInBelowAoi: 'ICH VERKAUFE IM ODER UNTER DEM AOI',
    notSellSupport: 'Ich verkaufe NICHT an der Unterstützung / Boden',
    selectDirFirst: 'Wähle zuerst eine Richtung im ersten Schritt',
    tradeSummary: 'TRADE ZUSAMMENFASSUNG',
    notesOptional: 'NOTIZEN (OPTIONAL)',
    notesPlaceholderLong: 'Trade Notizen, Beobachtungen...',
    readyToTradeLabel: 'BEREIT ZUM HANDELN',
    notRecommended: 'ZNPCV empfiehlt NICHT zu traden (min. 85%)',
    pointsBreakdown: 'PUNKTE BREAKDOWN',
    total: 'GESAMT',
    saveTrade: 'TRADE SPEICHERN',
    warningScore: 'Dein Score ist unter 85%. Nach ZNPCV Standard solltest du diesen Trade NICHT eingehen.',
    doNotEnter: 'TRADE NICHT EINGEHEN',
    saveAnyway: 'Trotzdem speichern',
    
    // Pattern names
    dblTop: 'DBL TOP',
    dblBtm: 'DBL BTM',
    hs: 'H&S',
    invHs: 'INV H&S',
    none: 'KEIN',
    
    // Trade History & Performance
    tradeHistory: 'TRADE HISTORY',
    performanceAnalytics: 'Performance Analytics & Trade Log',
    allTrades: 'ALLE TRADES',
    winLoss: 'WIN/LOSS',
    avgWinLoss: 'AVG WIN/LOSS',
    avgWin: 'AVG WIN',
    avgLoss: 'AVG LOSS',
    profitFactor: 'PROFIT FACTOR',
    avgRR: 'AVG R:R',
    bestTrade: 'BEST TRADE',
    consistency: 'CONSISTENCY',
    trades: 'TRADES',
    executed: 'AUSGEFÜHRT',
    pending: 'AUSSTEHEND',
    confirmDelete: 'Trade wirklich löschen?',
    
    // FAQ
    furtherQuestions: 'WEITERE FRAGEN?',
    contactUs: 'Wenn du weitere Fragen hast, kontaktiere uns gerne direkt',
  },
  en: {
    // Header
    online: 'ONLINE',
    localTime: 'LOCAL TIME',
    myAccount: 'MY ACCOUNT',
    logout: 'LOGOUT',
    login: 'LOGIN',
    editProfile: 'EDIT PROFILE',
    save: 'SAVE',
    
    // Home
    ultimateChecklist: 'ULTIMATE CHECKLIST',
    heroSubtitle: 'The ultimate trading checklist that has ever existed.',
    heroDesc: 'Professional Multi-Timeframe Analysis • Structured Decision Making • Maximum Discipline',
    newAnalysis: 'NEW ANALYSIS',
    newAnalysisDesc: 'Start your professional multi-timeframe analysis with the ultimate ZNPCV checklist',
    startNow: 'Start now',
    dashboard: 'DASHBOARD',
    dashboardDesc: 'Overview of your analyses, performance tracking and detailed statistics',
    openDashboard: 'Open',
    
    // Market Sessions
    marketSessions: 'MARKET SESSIONS',
    open: 'OPEN',
    closed: 'CLOSED',
    
    // Assets
    forex: 'FOREX',
    crypto: 'CRYPTO',
    stocks: 'STOCKS',
    commodities: 'COMMODITIES',
    indices: 'INDICES',
    
    // Features
    preciseAnalysis: 'PRECISE ANALYSIS',
    preciseAnalysisDesc: 'W-D-4H Confluence System for maximum accuracy',
    riskManagement: 'RISK MANAGEMENT',
    riskManagementDesc: 'Integrated R:R evaluation and SL/TP planning',
    performanceTracking: 'PERFORMANCE TRACKING',
    performanceTrackingDesc: 'Detailed statistics and success rates',
    
    // Footer
    sslEncrypted: 'SSL ENCRYPTED',
    gdprCompliant: 'GDPR COMPLIANT',
    dataProtection: 'DATA PROTECTION',
    worldwide: 'WORLDWIDE',
    contact: 'CONTACT',
    faqHelp: 'FAQ & HELP',
    footerDesc: 'The ultimate trading checklist for professional traders. Developed for maximum discipline and consistent results.',
    riskWarning: 'Trading involves risks. Past results are no guarantee of future profits.',
    allRights: 'All rights reserved.',
    
    // Checklist
    selectAsset: 'SELECT PAIR',
    selectAssetDesc: 'WHICH PAIR DO YOU WANT TO TRADE?',
    trendAnalysis: 'TREND ANALYSIS',
    trendAnalysisDesc: 'CHECK ALL 3 TIMEFRAMES',
    weekly: 'WEEKLY',
    daily: 'DAILY',
    fourHour: '4 HOUR',
    mainTrend: 'Main trend',
    midTerm: 'Mid-term',
    shortTerm: 'Short-term',
    bullish: 'BULLISH',
    bearish: 'BEARISH',
    confluence: 'CONFLUENCE',
    noConfluence: 'NO CONFLUENCE',
    allTimeframes: 'All timeframes show',
    dailyH4Sync: 'DAILY & 4H SYNC',
    higherProbability: 'Higher probability for a successful trade!',
    confluenceTooltip: 'Confluence means all timeframes (Weekly, Daily, 4H) point in the same direction. This increases the probability of success.',
    
    // AOI
    aoi: 'AREA OF INTEREST',
    aoiDesc: 'CHECK AOI ZONE',
    aoiDrawn: 'AOI MARKED',
    aoiDrawnDesc: 'Have you marked your Area of Interest in the chart?',
    priceInAoi: 'PRICE IN AOI',
    priceInAoiDesc: 'Is the current price in your AOI zone?',
    pricePosition: 'PRICE POSITION TO AOI',
    aboveAoi: 'ABOVE AOI',
    belowAoi: 'BELOW AOI',
    shortSetup: '= SHORT Setup',
    longSetup: '= LONG Setup',
    
    // Structure
    structureCheck: 'STRUCTURE CHECK',
    structureCheckDesc: 'CHECK PSS & EMA',
    pssRejected: 'PSS REJECTED',
    pssRejectedDesc: 'Previous Structure Support/Resistance was respected and rejected',
    emaRespected: 'EMA RESPECTED',
    emaRespectedDesc: 'Price has respected the moving average',
    structureConfirmed: 'STRUCTURE CONFIRMED',
    
    // Patterns
    patterns: 'CHART PATTERNS',
    patternsDesc: 'ONLY OUR PATTERNS',
    headShoulders: 'HEAD & SHOULDERS',
    invHeadShoulders: 'INVERSE HEAD & SHOULDERS',
    doubleTop: 'DOUBLE TOP',
    doubleBottom: 'DOUBLE BOTTOM',
    patternIdentified: 'PATTERN IDENTIFIED',
    patternIdentifiedDesc: 'One of our 4 patterns is visible in the chart',
    patternConfirmed: 'PATTERN CONFIRMED',
    patternConfirmedDesc: 'The pattern is complete and valid',
    
    // Entry
    entryConfirmation: 'ENTRY CONFIRMATION',
    entryConfirmationDesc: 'MSS & ENGULFING (30MIN - 1HR)',
    mssConfirmed: 'MSS / SOS CONFIRMED',
    mssConfirmedDesc: 'Market Structure Shift - Price has reversed (Bullish → Bearish or vice versa)',
    engulfingAfterPullback: 'ENGULFING AFTER PULLBACK',
    engulfingQuestion: 'Is the candle after pullback being engulfed?',
    blueEngulfing: 'BLUE ENGULFING',
    redEngulfing: 'RED ENGULFING',
    longEntry: '= LONG Entry',
    shortEntry: '= SHORT Entry',
    noEngulfing: 'NO ENGULFING',
    entrySignalConfirmed: 'ENTRY SIGNAL CONFIRMED',
    
    // Final
    finalCheck: 'FINAL CHECK',
    finalCheckDesc: 'IMPORTANT RULES',
    importantRules: 'IMPORTANT RULES',
    notBuyingResistance: 'DO NOT BUY AT RESISTANCE',
    notBuyingResistanceDesc: 'I do NOT buy at resistance',
    notSellingSupport: 'DO NOT SELL AT SUPPORT',
    notSellingSupportDesc: 'I do NOT sell at support',
    summary: 'SUMMARY',
    pair: 'PAIR',
    trend: 'TREND',
    mixed: 'MIXED',
    inAoi: 'IN AOI',
    entry: 'ENTRY',
    notes: 'NOTES',
    notesPlaceholder: 'Trade notes...',
    readyToTrade: 'READY TO TRADE',
    allConfirmed: 'All confirmations fulfilled!',
    
    // Navigation
    back: 'BACK',
    next: 'NEXT',
    save: 'SAVE',
    saving: 'SAVING...',
    loading: 'LOADING...',
    
    // Dashboard
    tradingDashboard: 'TRADING DASHBOARD',
    overviewStats: 'OVERVIEW & PERFORMANCE',
    totalAnalyses: 'TOTAL ANALYSES',
    readyToTradeShort: 'READY',
    inProgress: 'IN PROGRESS',
    withConfluence: 'WITH CONFLUENCE',
    activity30Days: 'ACTIVITY (30 DAYS)',
    lastAnalyses: 'LATEST ANALYSES',
    of: 'OF',
    noAnalyses: 'NO ANALYSES',
    startFirstAnalysis: 'START FIRST ANALYSIS',
    direction: 'DIRECTION',
    long: 'LONG',
    short: 'SHORT',
    calendar: 'CALENDAR',
    avgCompletion: 'AVERAGE COMPLETION',
    
    // Quotes
    quote1: '"Plan your trade, trade your plan."',
    quote2: '"Discipline determines success or failure."',
    quote3: '"We don\'t buy at resistance, we don\'t sell at support."',
    quote4: '"Patience is the key to success in trading."',
    quote5: '"Risk management is more important than profit maximization."',
    
    // Warning
    warningTitle: 'WARNING - NOT AN A+++ TRADE',
    warningDesc: 'Your checklist is below 85%. According to ZNPCV standards, you should only enter A+++ trades. Review all criteria again or skip this trade.',
    warningButton: 'DO NOT ENTER TRADE',
    proceedAnyway: 'Proceed anyway',
    aPlusTradeOnly: 'A+++ TRADES ONLY',
    
    // Additional translations
    features: 'FEATURES',
    featuresDesc: 'Professional Trading Tools',
    znpcvStandard: 'ZNPCV STANDARD',
    stepChecklist: 'STEP CHECKLIST',
    chartPatterns: 'CHART PATTERNS',
    tradingTools: 'THE ULTIMATE TRADING TOOL',
    philosophy: 'ZNPCV PHILOSOPHY',
    disciplineQuote: 'Discipline beats talent. Every. Single. Day.',
    
    // Risk Management
    accountSize: 'ACCOUNT SIZE',
    riskPercent: 'RISK %',
    entryPrice: 'ENTRY PRICE',
    stopLoss: 'STOP LOSS',
    takeProfit: 'TAKE PROFIT',
    lotSizeCalc: 'LOT SIZE CALCULATOR',
    recommendedLotSize: 'RECOMMENDED LOT SIZE',
    standardLots: 'Standard Lots',
    miniLots: 'MINI LOTS',
    microLots: 'MICRO LOTS',
    units: 'UNITS',
    riskAmount: 'RISK $',
    slPips: 'SL PIPS',
    tpPips: 'TP PIPS',
    potentialProfit: 'POTENTIAL PROFIT',
    rrRatio: 'R:R RATIO',
    quickRisk: 'QUICK RISK SELECTION',
    lotSizeInfo: 'Calculate your exact lot size based on your risk. Enter Entry & Stop Loss to see the recommended position.',
    enterEntryAndSL: 'Enter Entry Price and Stop Loss to calculate your Lot Size',
    minRRWarning: 'ZNPCV recommends at least 1:2.5 R:R ratio',
    goodRR: 'Good Risk:Reward ratio!',
    tradeLevels: 'TRADE LEVELS',
    
    // Checklist specific
    assetDirection: 'ASSET & DIRECTION',
    selectPairDirection: 'Select your trading pair and trade direction',
    goldenRules: 'ZNPCV RULE',
    goldenRuleText: 'Don\'t buy at resistance • Don\'t sell at support',
    longBuyRule: 'We buy IN the AOI or ABOVE the AOI (Support)',
    shortSellRule: 'We sell IN the AOI or BELOW the AOI (Resistance)',
    neverBottomTop: 'NEVER SELL AT THE BOTTOM! NEVER BUY AT THE TOP!',
    selectDirection: 'SELECT YOUR DIRECTION',
    buyInAoi: 'Buy in/above AOI',
    sellInAoi: 'Sell in/below AOI',
    weeklyAnalysis: 'WEEKLY ANALYSIS',
    weeklyConfirm: 'Weekly Timeframe Confirmations (max 60%)',
    weeklyScore: 'WEEKLY SCORE',
    weeklyTrend: 'WEEKLY TREND (BULLISH / BEARISH)',
    atAoiRejected: 'AT AOI / REJECTED',
    atAoiDesc: 'Price is at AOI OR Price rejects AOI',
    touchingEma: 'TOUCHING / REJECTING EMA',
    touchingEmaDesc: 'Candles touch OR reject the EMA',
    candlestickRejection: 'CANDLESTICK REJECTION',
    candlestickDesc: 'Candle shows clear rejection (Pinbar, Doji, Hammer)',
    rejectionPsp: 'REJECTION FROM PSP',
    rejectionPspDesc: 'Rejection from Previous Structure Point',
    roundLevel: 'ROUND PSYCH LEVEL',
    roundLevelDesc: 'Price is at OR rejects round number',
    swingHighLow: 'SWING HIGH / SWING LOW',
    swingDesc: 'Price has reached Swing High OR Swing Low',
    patternWeekly: 'PATTERN (WEEKLY)',
    patternDesc: 'Double Top/Bottom, Normal/Inverted H&S',
    dailyAnalysis: 'DAILY ANALYSIS',
    dailyConfirm: 'Daily Timeframe Confirmations (max 60%)',
    dailyScore: 'DAILY SCORE',
    dailyTrend: 'DAILY TREND (BULLISH / BEARISH)',
    h4Analysis: '4H ANALYSIS',
    h4Confirm: 'Lower Timeframe Confirmation (max 35%)',
    h4Score: '4H SCORE',
    h4Trend: '4H TREND (BULLISH / BEARISH)',
    entryChecklist: 'ENTRY CHECKLIST',
    entryConfirm: 'Entry Confirmations (max 25%)',
    entryTimeframe: 'ENTRY TIMEFRAME',
    entryTimeframeDesc: 'Choose between 30min or 1H - based on cleanest structure and most precise entry (Swing/Day Trading)',
    entryScoreLabel: 'ENTRY SCORE',
    mssShift: 'MSS - MARKET STRUCTURE SHIFT',
    mssDesc: 'Shift of Structure / Market structure has shifted (30min-1hr)',
    engulfingCandle: 'ENGULFING CANDLESTICK',
    engulfingDesc: 'Engulfing candle visible after pullback (Reversal Confirmation)',
    patternIfAny: 'PATTERN (IF THERE IS ONE)',
    patternIfAnyDesc: 'If a pattern is visible on Entry TF',
    entryTrigger: 'ENTRY TRIGGER TYPE',
    pinbarRejection: 'PINBAR REJECTION',
    engulfing: 'ENGULFING',
    riskManagementTitle: 'RISK MANAGEMENT',
    riskManagementSubtitle: 'Position Sizing & Lot Size Calculator',
    finalCheckTitle: 'FINAL CHECK',
    finalCheckSubtitle: 'Final confirmation before the trade',
    confirmRule: 'CONFIRM THE ZNPCV RULE',
    buyInAboveAoi: 'I BUY IN OR ABOVE THE AOI',
    notBuyResistance: 'I do NOT buy at resistance / top',
    sellInBelowAoi: 'I SELL IN OR BELOW THE AOI',
    notSellSupport: 'I do NOT sell at support / bottom',
    selectDirFirst: 'Select a direction in the first step first',
    tradeSummary: 'TRADE SUMMARY',
    notesOptional: 'NOTES (OPTIONAL)',
    notesPlaceholderLong: 'Trade notes, observations...',
    readyToTradeLabel: 'READY TO TRADE',
    notRecommended: 'ZNPCV recommends NOT to trade (min. 85%)',
    pointsBreakdown: 'POINTS BREAKDOWN',
    total: 'TOTAL',
    saveTrade: 'SAVE TRADE',
    warningScore: 'Your score is below 85%. According to ZNPCV standard, you should NOT enter this trade.',
    doNotEnter: 'DO NOT ENTER TRADE',
    saveAnyway: 'Save anyway',
    
    // Pattern names
    dblTop: 'DBL TOP',
    dblBtm: 'DBL BTM',
    hs: 'H&S',
    invHs: 'INV H&S',
    none: 'NONE',
    
    // Trade History & Performance
    tradeHistory: 'TRADE HISTORY',
    performanceAnalytics: 'Performance Analytics & Trade Log',
    allTrades: 'ALL TRADES',
    winLoss: 'WIN/LOSS',
    avgWinLoss: 'AVG WIN/LOSS',
    avgWin: 'AVG WIN',
    avgLoss: 'AVG LOSS',
    profitFactor: 'PROFIT FACTOR',
    avgRR: 'AVG R:R',
    bestTrade: 'BEST TRADE',
    consistency: 'CONSISTENCY',
    trades: 'TRADES',
    executed: 'EXECUTED',
    pending: 'PENDING',
    confirmDelete: 'Really delete this trade?',
    
    // FAQ
    furtherQuestions: 'MORE QUESTIONS?',
    contactUs: 'If you have more questions, feel free to contact us directly',
  },
  fa: {
    // Header
    online: 'آنلاین',
    localTime: 'ساعت محلی',
    
    // Home
    ultimateChecklist: 'چک‌لیست نهایی',
    heroSubtitle: 'بهترین چک‌لیست معاملاتی که تا به حال وجود داشته است.',
    heroDesc: 'تحلیل چند تایم‌فریم حرفه‌ای • تصمیم‌گیری ساختاریافته • حداکثر انضباط',
    newAnalysis: 'تحلیل جدید',
    newAnalysisDesc: 'تحلیل چند تایم‌فریم حرفه‌ای خود را با چک‌لیست نهایی ZNPCV شروع کنید',
    startNow: 'شروع کنید',
    dashboard: 'داشبورد',
    dashboardDesc: 'نمای کلی تحلیل‌ها، پیگیری عملکرد و آمار دقیق',
    openDashboard: 'باز کردن',
    
    // Market Sessions
    marketSessions: 'جلسات بازار',
    open: 'باز',
    closed: 'بسته',
    
    // Assets
    forex: 'فارکس',
    crypto: 'کریپتو',
    stocks: 'سهام',
    commodities: 'کالاها',
    indices: 'شاخص‌ها',
    
    // Features
    preciseAnalysis: 'تحلیل دقیق',
    preciseAnalysisDesc: 'سیستم هم‌پوشانی W-D-4H برای حداکثر دقت',
    riskManagement: 'مدیریت ریسک',
    riskManagementDesc: 'ارزیابی R:R یکپارچه و برنامه‌ریزی SL/TP',
    performanceTracking: 'پیگیری عملکرد',
    performanceTrackingDesc: 'آمار دقیق و نرخ موفقیت',
    
    // Footer
    sslEncrypted: 'رمزگذاری SSL',
    gdprCompliant: 'مطابق GDPR',
    dataProtection: 'حفاظت داده',
    worldwide: 'جهانی',
    contact: 'تماس',
    faqHelp: 'سوالات متداول و راهنما',
    footerDesc: 'چک‌لیست نهایی معاملاتی برای معامله‌گران حرفه‌ای. طراحی شده برای حداکثر انضباط و نتایج پایدار.',
    riskWarning: 'معامله‌گری شامل ریسک است. نتایج گذشته تضمینی برای سود آینده نیست.',
    allRights: 'تمامی حقوق محفوظ است.',
    
    // Checklist
    selectAsset: 'انتخاب جفت ارز',
    selectAssetDesc: 'کدام جفت ارز را می‌خواهید معامله کنید؟',
    trendAnalysis: 'تحلیل روند',
    trendAnalysisDesc: 'هر ۳ تایم‌فریم را بررسی کنید',
    weekly: 'هفتگی',
    daily: 'روزانه',
    fourHour: '۴ ساعته',
    mainTrend: 'روند اصلی',
    midTerm: 'میان‌مدت',
    shortTerm: 'کوتاه‌مدت',
    bullish: 'صعودی',
    bearish: 'نزولی',
    confluence: 'هم‌پوشانی',
    noConfluence: 'بدون هم‌پوشانی',
    allTimeframes: 'همه تایم‌فریم‌ها نشان می‌دهند',
    dailyH4Sync: 'همگام روزانه و ۴ ساعته',
    higherProbability: 'احتمال بالاتر برای معامله موفق!',
    confluenceTooltip: 'هم‌پوشانی یعنی همه تایم‌فریم‌ها (هفتگی، روزانه، ۴ ساعته) در یک جهت هستند. این احتمال موفقیت را افزایش می‌دهد.',
    
    // AOI
    aoi: 'منطقه مورد علاقه',
    aoiDesc: 'منطقه AOI را بررسی کنید',
    aoiDrawn: 'AOI مشخص شده',
    aoiDrawnDesc: 'آیا منطقه مورد علاقه خود را در چارت مشخص کرده‌اید؟',
    priceInAoi: 'قیمت در AOI',
    priceInAoiDesc: 'آیا قیمت فعلی در منطقه AOI شما است؟',
    pricePosition: 'موقعیت قیمت نسبت به AOI',
    aboveAoi: 'بالای AOI',
    belowAoi: 'پایین AOI',
    shortSetup: '= ستاپ فروش',
    longSetup: '= ستاپ خرید',
    
    // Structure
    structureCheck: 'بررسی ساختار',
    structureCheckDesc: 'PSS و EMA را بررسی کنید',
    pssRejected: 'PSS رد شده',
    pssRejectedDesc: 'ساختار قبلی (حمایت/مقاومت) احترام گذاشته و رد شده',
    emaRespected: 'EMA احترام گذاشته شده',
    emaRespectedDesc: 'قیمت میانگین متحرک را احترام گذاشته',
    structureConfirmed: 'ساختار تایید شده',
    
    // Patterns
    patterns: 'الگوهای چارت',
    patternsDesc: 'فقط الگوهای ما',
    headShoulders: 'سر و شانه',
    invHeadShoulders: 'سر و شانه معکوس',
    doubleTop: 'سقف دوقلو',
    doubleBottom: 'کف دوقلو',
    patternIdentified: 'الگو شناسایی شده',
    patternIdentifiedDesc: 'یکی از ۴ الگوی ما در چارت قابل مشاهده است',
    patternConfirmed: 'الگو تایید شده',
    patternConfirmedDesc: 'الگو کامل و معتبر است',
    
    // Entry
    entryConfirmation: 'تایید ورود',
    entryConfirmationDesc: 'MSS و ENGULFING (۳۰ دقیقه - ۱ ساعت)',
    mssConfirmed: 'MSS / SOS تایید شده',
    mssConfirmedDesc: 'تغییر ساختار بازار - قیمت چرخیده (صعودی → نزولی یا برعکس)',
    engulfingAfterPullback: 'ENGULFING پس از پولبک',
    engulfingQuestion: 'آیا کندل پس از پولبک بلعیده می‌شود؟',
    blueEngulfing: 'ENGULFING آبی',
    redEngulfing: 'ENGULFING قرمز',
    longEntry: '= ورود خرید',
    shortEntry: '= ورود فروش',
    noEngulfing: 'بدون ENGULFING',
    entrySignalConfirmed: 'سیگنال ورود تایید شده',
    
    // Final
    finalCheck: 'بررسی نهایی',
    finalCheckDesc: 'قوانین مهم',
    importantRules: 'قوانین مهم',
    notBuyingResistance: 'در مقاومت خرید نکنید',
    notBuyingResistanceDesc: 'من در مقاومت خرید نمی‌کنم',
    notSellingSupport: 'در حمایت فروش نکنید',
    notSellingSupportDesc: 'من در حمایت فروش نمی‌کنم',
    summary: 'خلاصه',
    pair: 'جفت ارز',
    trend: 'روند',
    mixed: 'مختلط',
    inAoi: 'در AOI',
    entry: 'ورود',
    notes: 'یادداشت‌ها',
    notesPlaceholder: 'یادداشت‌های معامله...',
    readyToTrade: 'آماده معامله',
    allConfirmed: 'همه تاییدیه‌ها انجام شده!',
    
    // Navigation
    back: 'قبلی',
    next: 'بعدی',
    save: 'ذخیره',
    saving: 'در حال ذخیره...',
    loading: 'در حال بارگذاری...',
    
    // Dashboard
    tradingDashboard: 'داشبورد معاملات',
    overviewStats: 'نمای کلی و عملکرد',
    totalAnalyses: 'کل تحلیل‌ها',
    readyToTradeShort: 'آماده',
    inProgress: 'در حال انجام',
    withConfluence: 'با هم‌پوشانی',
    activity30Days: 'فعالیت (۳۰ روز)',
    lastAnalyses: 'آخرین تحلیل‌ها',
    of: 'از',
    noAnalyses: 'بدون تحلیل',
    startFirstAnalysis: 'اولین تحلیل را شروع کنید',
    direction: 'جهت',
    long: 'خرید',
    short: 'فروش',
    calendar: 'تقویم',
    avgCompletion: 'میانگین تکمیل',
    
    // Quotes
    quote1: '"معامله‌ات را برنامه‌ریزی کن، برنامه‌ات را معامله کن."',
    quote2: '"انضباط موفقیت یا شکست را تعیین می‌کند."',
    quote3: '"ما در مقاومت نمی‌خریم، در حمایت نمی‌فروشیم."',
    quote4: '"صبر کلید موفقیت در معامله‌گری است."',
    quote5: '"مدیریت ریسک مهم‌تر از حداکثر کردن سود است."',
    
    // Warning
    warningTitle: 'هشدار - معامله A+++ نیست',
    warningDesc: 'چک‌لیست شما زیر ۸۵٪ است. طبق استاندارد ZNPCV فقط باید وارد معاملات A+++ شوید. همه معیارها را دوباره بررسی کنید یا این معامله را رد کنید.',
    warningButton: 'وارد معامله نشوید',
    proceedAnyway: 'به هر حال ادامه دهید',
    aPlusTradeOnly: 'فقط معاملات A+++',
    
    // Additional translations
    features: 'ویژگی‌ها',
    featuresDesc: 'ابزارهای معاملاتی حرفه‌ای',
    znpcvStandard: 'استاندارد ZNPCV',
    stepChecklist: 'چک‌لیست مراحل',
    chartPatterns: 'الگوهای نموداری',
    tradingTools: 'ابزار نهایی معاملات',
    philosophy: 'فلسفه ZNPCV',
    disciplineQuote: 'انضباط استعداد را شکست می‌دهد. هر. روز.',
    
    // Risk Management
    accountSize: 'اندازه حساب',
    riskPercent: 'ریسک %',
    entryPrice: 'قیمت ورود',
    stopLoss: 'حد ضرر',
    takeProfit: 'حد سود',
    lotSizeCalc: 'محاسبه‌گر لات',
    recommendedLotSize: 'لات پیشنهادی',
    standardLots: 'لات استاندارد',
    miniLots: 'مینی لات',
    microLots: 'میکرو لات',
    units: 'واحد',
    riskAmount: 'مقدار ریسک $',
    slPips: 'پیپ SL',
    tpPips: 'پیپ TP',
    potentialProfit: 'سود بالقوه',
    rrRatio: 'نسبت R:R',
    quickRisk: 'انتخاب سریع ریسک',
    lotSizeInfo: 'لات دقیق خود را بر اساس ریسک محاسبه کنید. Entry و Stop Loss را وارد کنید.',
    enterEntryAndSL: 'قیمت ورود و حد ضرر را وارد کنید تا لات محاسبه شود',
    minRRWarning: 'ZNPCV حداقل نسبت 1:2.5 را توصیه می‌کند',
    goodRR: 'نسبت ریسک به ریوارد خوب!',
    tradeLevels: 'سطوح معامله',
    
    // Checklist specific
    assetDirection: 'دارایی و جهت',
    selectPairDirection: 'جفت ارز و جهت معامله را انتخاب کنید',
    goldenRules: 'قانون طلایی ZNPCV',
    goldenRuleText: 'هرگز در مقاومت خرید نکنید. هرگز در حمایت نفروشید. معامله لانگ فقط در یا بالای AOI انجام می‌شود (ناحیه حمایت). معامله شورت فقط در یا زیر AOI انجام می‌شود (ناحیه مقاومت).',
    longBuyRule: 'ما در AOI یا بالای AOI خرید می‌کنیم (حمایت)',
    shortSellRule: 'ما در AOI یا زیر AOI می‌فروشیم (مقاومت)',
    neverBottomTop: 'هرگز در کف نفروشید! هرگز در سقف نخرید!',
    selectDirection: 'جهت را انتخاب کنید',
    buyInAoi: 'خرید در/بالای AOI',
    sellInAoi: 'فروش در/زیر AOI',
    weeklyAnalysis: 'تحلیل هفتگی',
    weeklyConfirm: 'تاییدیه‌های تایم‌فریم هفتگی (حداکثر ۶۰٪)',
    weeklyScore: 'امتیاز هفتگی',
    weeklyTrend: 'روند هفتگی (صعودی / نزولی)',
    atAoiRejected: 'در AOI / رد شده',
    atAoiDesc: 'قیمت در AOI است یا AOI را رد می‌کند',
    touchingEma: 'لمس / رد EMA',
    touchingEmaDesc: 'کندل‌ها EMA را لمس یا رد می‌کنند',
    candlestickRejection: 'رد کندل',
    candlestickDesc: 'کندل رد واضح نشان می‌دهد (Pinbar، Doji، Hammer)',
    rejectionPsp: 'رد از PSP',
    rejectionPspDesc: 'رد از نقطه ساختار قبلی',
    roundLevel: 'سطح روانی گرد',
    roundLevelDesc: 'قیمت در عدد گرد است یا آن را رد می‌کند',
    swingHighLow: 'سقف / کف سوئینگ',
    swingDesc: 'قیمت به سقف یا کف سوئینگ رسیده است',
    patternWeekly: 'الگو (هفتگی)',
    patternDesc: 'سقف/کف دوقلو، سر و شانه معمولی/معکوس',
    dailyAnalysis: 'تحلیل روزانه',
    dailyConfirm: 'تاییدیه‌های تایم‌فریم روزانه (حداکثر ۶۰٪)',
    dailyScore: 'امتیاز روزانه',
    dailyTrend: 'روند روزانه (صعودی / نزولی)',
    h4Analysis: 'تحلیل ۴ ساعته',
    h4Confirm: 'تاییدیه تایم‌فریم پایین (حداکثر ۳۵٪)',
    h4Score: 'امتیاز ۴ ساعته',
    h4Trend: 'روند ۴ ساعته (صعودی / نزولی)',
    entryChecklist: 'چک‌لیست ورود',
    entryConfirm: 'تاییدیه‌های ورود (حداکثر ۲۵٪)',
    entryTimeframe: 'تایم‌فریم ورود',
    entryTimeframeDesc: 'بین ۳۰ دقیقه یا ۱ ساعت انتخاب کنید - بسته به اینکه کدام تمیزترین ساختار و دقیق‌ترین ورود را ارائه می‌دهد. ما تریدرهای سوئینگ/دی هستیم که بر تایم‌فریم‌های بالاتر تمرکز داریم، نه اسکالپر.',
    entryScoreLabel: 'امتیاز ورود',
    mssShift: 'MSS - تغییر ساختار بازار',
    mssDesc: 'تغییر ساختار / ساختار بازار تغییر کرده است',
    engulfingCandle: 'کندل انگالفینگ',
    engulfingDesc: 'کندل انگالفینگ بعد از پولبک (تایید برگشت)',
    patternIfAny: 'الگو (در صورت وجود)',
    patternIfAnyDesc: 'اگر الگویی در تایم‌فریم ورود وجود دارد',
    entryTrigger: 'نوع تریگر ورود',
    pinbarRejection: 'رد پین‌بار',
    engulfing: 'انگالفینگ',
    riskManagementTitle: 'مدیریت ریسک',
    riskManagementSubtitle: 'اندازه‌گیری پوزیشن و محاسبه‌گر لات',
    finalCheckTitle: 'بررسی نهایی',
    finalCheckSubtitle: 'تایید نهایی قبل از معامله',
    confirmRule: 'قانون ZNPCV را تایید کنید',
    buyInAboveAoi: 'من در یا بالای AOI می‌خرم',
    notBuyResistance: 'من در مقاومت / سقف نمی‌خرم',
    sellInBelowAoi: 'من در یا زیر AOI می‌فروشم',
    notSellSupport: 'من در حمایت / کف نمی‌فروشم',
    selectDirFirst: 'ابتدا جهت را در مرحله اول انتخاب کنید',
    tradeSummary: 'خلاصه معامله',
    notesOptional: 'یادداشت‌ها (اختیاری)',
    notesPlaceholderLong: 'یادداشت‌های معامله، مشاهدات...',
    readyToTradeLabel: 'آماده معامله',
    notRecommended: 'ZNPCV توصیه می‌کند معامله نکنید (حداقل ۸۵٪)',
    pointsBreakdown: 'تفکیک امتیازات',
    total: 'مجموع',
    saveTrade: 'ذخیره معامله',
    warningScore: 'امتیاز شما زیر ۸۵٪ است. طبق استاندارد ZNPCV نباید وارد این معامله شوید.',
    doNotEnter: 'وارد معامله نشوید',
    saveAnyway: 'به هر حال ذخیره کنید',
    
    // Pattern names
    dblTop: 'سقف دوقلو',
    dblBtm: 'کف دوقلو',
    hs: 'سر و شانه',
    invHs: 'سر و شانه معکوس',
    none: 'هیچ',
    
    // Trade History & Performance
    tradeHistory: 'تاریخچه معاملات',
    performanceAnalytics: 'تحلیل عملکرد و ثبت معاملات',
    allTrades: 'همه معاملات',
    winLoss: 'برد/باخت',
    avgWinLoss: 'میانگین برد/باخت',
    avgWin: 'میانگین برد',
    avgLoss: 'میانگین باخت',
    profitFactor: 'ضریب سود',
    avgRR: 'میانگین R:R',
    bestTrade: 'بهترین معامله',
    consistency: 'ثبات',
    trades: 'معاملات',
    executed: 'اجرا شده',
    pending: 'در انتظار',
    confirmDelete: 'واقعاً می‌خواهید معامله را حذف کنید؟',
    
    // FAQ
    furtherQuestions: 'سوالات بیشتر؟',
    contactUs: 'اگر سوال بیشتری دارید، با ما تماس بگیرید',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('znpcv_language') || 'de';
    }
    return 'de';
  });

  const [darkMode, setDarkMode] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('znpcv_darkmode') !== 'false';
    }
    return true;
  });

  useEffect(() => {
    localStorage.setItem('znpcv_language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('znpcv_darkmode', darkMode.toString());
  }, [darkMode]);

  const t = (key) => translations[language][key] || key;
  
  const toggleLanguage = () => {
    const langs = ['de', 'en', 'fa', 'zh', 'es', 'fr', 'ar', 'hi', 'ja', 'pt'];
    const currentIndex = langs.indexOf(language);
    setLanguage(langs[(currentIndex + 1) % langs.length]);
  };

  const toggleDarkMode = () => setDarkMode(!darkMode);
  
  const isRTL = language === 'fa' || language === 'ar' || language === 'hi';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, isRTL, darkMode, setDarkMode, toggleDarkMode }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function LanguageToggle() {
  const { language, setLanguage, darkMode } = useLanguage();
  const [isOpen, setIsOpen] = React.useState(false);
  
  const languages = [
    { code: 'de', label: 'DE' },
    { code: 'en', label: 'EN' },
    { code: 'zh', label: 'ZH' },
    { code: 'es', label: 'ES' },
    { code: 'fr', label: 'FR' },
    { code: 'pt', label: 'PT' },
    { code: 'hi', label: 'HI' },
    { code: 'ja', label: 'JA' },
    { code: 'ar', label: 'AR' },
    { code: 'fa', label: 'FA' }
  ];
  
  const currentLang = languages.find(l => l.code === language) || languages[0];
  
  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`flex items-center gap-2 px-3 py-2 rounded-xl border-2 transition-all ${
          darkMode ? 'bg-zinc-900 border-zinc-800 hover:border-zinc-700 text-white' : 'bg-zinc-100 border-zinc-300 hover:border-zinc-400 text-black'
        }`}
      >
        <span className="text-xs font-bold tracking-widest">{currentLang.label}</span>
        <svg className={`w-3 h-3 transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      
      {isOpen && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setIsOpen(false)} />
          <div className={`absolute right-0 mt-2 w-40 rounded-xl border-2 shadow-2xl z-20 overflow-hidden ${
            darkMode ? 'bg-zinc-900 border-zinc-800' : 'bg-white border-zinc-300'
          }`}>
            <div className="grid grid-cols-2 gap-1 p-2">
              {languages.map((lang) => (
                <button
                  key={lang.code}
                  onClick={() => {
                    setLanguage(lang.code);
                    setIsOpen(false);
                  }}
                  className={`px-3 py-2 rounded-lg transition-all text-xs font-bold tracking-widest ${
                    language === lang.code 
                      ? darkMode 
                        ? 'bg-white text-black' 
                        : 'bg-zinc-900 text-white'
                      : darkMode 
                        ? 'text-zinc-400 hover:text-white hover:bg-zinc-800' 
                        : 'text-zinc-600 hover:text-black hover:bg-zinc-100'
                  }`}
                >
                  {lang.label}
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export function DarkModeToggle() {
  const { darkMode, toggleDarkMode } = useLanguage();
  
  return (
    <button
      onClick={toggleDarkMode}
      className={`p-2 rounded-lg transition-colors ${
        darkMode 
          ? 'bg-zinc-800 text-yellow-400 hover:bg-zinc-700' 
          : 'bg-zinc-200 text-zinc-700 hover:bg-zinc-300'
      }`}
      title={darkMode ? 'Light Mode' : 'Dark Mode'}
    >
      {darkMode ? (
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="4"/>
          <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>
        </svg>
      ) : (
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
        </svg>
      )}
    </button>
  );
}